/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import Proccess.BienTheSanPham;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author Admin
 */
public class frmBienTheSanPham extends javax.swing.JFrame {
    private BienTheSanPham dao = new BienTheSanPham();
    private DefaultTableModel model;
    private boolean isAdding = false;
    private int currentMaSP; // Mã sản phẩm đang chọn từ frmSanPham
    private Runnable onDataChanged; // Callback
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmBienTheSanPham.class.getName());

    /**
     * Creates new form frmBienTheSanPham
     */
    public frmBienTheSanPham(int maSP) {
        initComponents();
        model = (DefaultTableModel) tbbienthesanpham.getModel();
        this.currentMaSP = maSP;

        loadComboBox();
        loadData();

        setButton(true);
        setEnableFields(false);

        txtma.setEnabled(false); // Mã biến thể auto
        cbmsp.setSelectedItem(maSP);
        cbmsp.setEnabled(false);
    }
 public void setOnDataChanged(Runnable callback) {
        this.onDataChanged = callback;
    }

    private void loadComboBox() {
        cbmausac.removeAllItems();
        cbmausac.addItem("Đỏ");
        cbmausac.addItem("Xanh");
        cbmausac.addItem("Vàng");
        cbmausac.addItem("Đen");
        cbmausac.addItem("Trắng");

        cbkichco.removeAllItems();
        cbkichco.addItem("S");
        cbkichco.addItem("M");
        cbkichco.addItem("L");
        cbkichco.addItem("XL");

        cbmsp.removeAllItems();
        cbmsp.addItem(String.valueOf(currentMaSP)); // Mặc định mã SP hiện tại
    }

    private void loadData() {
        List<BienTheSanPham> list = dao.getListByMaSP(currentMaSP);
        model.setRowCount(0);
        for (BienTheSanPham bt : list) {
            model.addRow(new Object[]{
                bt.getMa(), bt.getMaSP(), bt.getMauSac(), bt.getKichCo(), bt.getSoLuong()
            });
        }
    }

    private void clearFields() {
        txtma.setText("");
        cbmausac.setSelectedIndex(-1);
        cbkichco.setSelectedIndex(-1);
        txtsoluong.setText("");
    }

    private void setButton(boolean enable) {
        btthem.setEnabled(enable);
        btsua.setEnabled(enable);
        btxoa.setEnabled(enable);
        btluu.setEnabled(!enable);
        btkluu.setEnabled(!enable);
    }

    private void setEnableFields(boolean enable) {
        cbmausac.setEnabled(enable);
        cbkichco.setEnabled(enable);
        txtsoluong.setEnabled(enable);
    }

    private void fillToForm() {
        int row = tbbienthesanpham.getSelectedRow();
        if (row < 0) return;
        txtma.setText(tbbienthesanpham.getValueAt(row, 0).toString());
        cbmsp.setSelectedItem(tbbienthesanpham.getValueAt(row, 1).toString());
        cbmausac.setSelectedItem(tbbienthesanpham.getValueAt(row, 2).toString());
        cbkichco.setSelectedItem(tbbienthesanpham.getValueAt(row, 3).toString());
        txtsoluong.setText(tbbienthesanpham.getValueAt(row, 4).toString());
    }

    private boolean validateInput() {
        if (cbmausac.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Màu sắc không được để trống!");
            cbmausac.requestFocus();
            return false;
        }
        if (cbkichco.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Kích cỡ không được để trống!");
            cbkichco.requestFocus();
            return false;
        }
        try {
            Integer.parseInt(txtsoluong.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên!");
            txtsoluong.requestFocus();
            return false;
        }
        return true;
    }

    // Kiểm tra trùng màu + kích cỡ
    private boolean isDuplicate(String mau, String kichCo) {
        for (int i = 0; i < tbbienthesanpham.getRowCount(); i++) {
            String existingMau = tbbienthesanpham.getValueAt(i, 2).toString();
            String existingKichCo = tbbienthesanpham.getValueAt(i, 3).toString();
            if (existingMau.equalsIgnoreCase(mau) && existingKichCo.equalsIgnoreCase(kichCo)) {
                if (!isAdding && tbbienthesanpham.getValueAt(i, 0).toString().equals(txtma.getText())) {
                    continue; // khi sửa cùng bản ghi thì bỏ qua
                }
                return true;
            }
        }
        return false;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        btluu = new javax.swing.JButton();
        btkluu = new javax.swing.JButton();
        btthoat = new javax.swing.JButton();
        cbkichco = new javax.swing.JComboBox<>();
        cbmausac = new javax.swing.JComboBox<>();
        cbmsp = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbienthesanpham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 121, 227));
        jLabel1.setText("Biến thể sản phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mã sản phẩm:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Màu sắc:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kích cỡ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng:");

        btthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btxoa.setText("Xóa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        btluu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btluu.setText("Lưu");
        btluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuActionPerformed(evt);
            }
        });

        btkluu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btkluu.setText("K.Lưu");
        btkluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkluuActionPerformed(evt);
            }
        });

        btthoat.setBackground(new java.awt.Color(255, 239, 117));
        btthoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btthoat.setText("Thoát");
        btthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthoatActionPerformed(evt);
            }
        });

        cbmsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbmsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbkichco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btthem)
                .addGap(35, 35, 35)
                .addComponent(btsua)
                .addGap(37, 37, 37)
                .addComponent(btxoa)
                .addGap(36, 36, 36)
                .addComponent(btluu)
                .addGap(41, 41, 41)
                .addComponent(btkluu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btthoat)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbmausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cbkichco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(btsua)
                    .addComponent(btxoa)
                    .addComponent(btluu)
                    .addComponent(btkluu)
                    .addComponent(btthoat))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        tbbienthesanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Mã sản phẩm", "Màu sắc", "Kích cỡ", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbbienthesanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbienthesanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbbienthesanpham);
        if (tbbienthesanpham.getColumnModel().getColumnCount() > 0) {
            tbbienthesanpham.getColumnModel().getColumn(0).setResizable(false);
            tbbienthesanpham.getColumnModel().getColumn(1).setResizable(false);
            tbbienthesanpham.getColumnModel().getColumn(2).setResizable(false);
            tbbienthesanpham.getColumnModel().getColumn(3).setResizable(false);
            tbbienthesanpham.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        isAdding = true;
        clearFields();
        setEnableFields(true);
        setButton(false);
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        int row = tbbienthesanpham.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn biến thể để sửa!");
            return;
        }
        setEnableFields(true);
        setButton(false);
        txtma.setEnabled(false);
        cbmsp.setEnabled(false);
    }//GEN-LAST:event_btsuaActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        int row = tbbienthesanpham.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn biến thể để xóa!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        int ma = Integer.parseInt(tbbienthesanpham.getValueAt(row, 0).toString());
        dao.setMa(ma);
        if (dao.deleteBienThe()) {
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            loadData();
            clearFields();
            if (onDataChanged != null) onDataChanged.run();
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        // TODO add your handling code here:
        if (!validateInput()) return;

        String mau = cbmausac.getSelectedItem().toString();
        String kichCo = cbkichco.getSelectedItem().toString();
        int soLuong = Integer.parseInt(txtsoluong.getText().trim());

        if (isAdding && isDuplicate(mau, kichCo)) {
            JOptionPane.showMessageDialog(this, "Biến thể đã tồn tại!");
            return;
        }

        dao.setMaSP(currentMaSP);
        dao.setMauSac(mau);
        dao.setKichCo(kichCo);
        dao.setSoLuong(soLuong);

        boolean success;
        if (isAdding) {
            success = dao.addBienThe();
        } else {
            dao.setMa(Integer.parseInt(txtma.getText().trim()));
            success = dao.updateBienThe();
        }

        if (success) {
            JOptionPane.showMessageDialog(this, "Thành công!");
            loadData();
            clearFields();
            setEnableFields(false);
            setButton(true);
            isAdding = false;
            if (onDataChanged != null) onDataChanged.run();
        } else {
            JOptionPane.showMessageDialog(this, "Thất bại!");
        }

    }//GEN-LAST:event_btluuActionPerformed

    private void btkluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkluuActionPerformed
        // TODO add your handling code here:
        clearFields();
        setEnableFields(false);
        setButton(true);
        isAdding = false;
    }//GEN-LAST:event_btkluuActionPerformed

    private void btthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btthoatActionPerformed

    private void tbbienthesanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbienthesanphamMouseClicked
        // TODO add your handling code here:
        fillToForm();
    }//GEN-LAST:event_tbbienthesanphamMouseClicked

    private void cbmspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> new frmBienTheSanPham(1).setVisible(true)); // test với MaSP = 1
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btkluu;
    private javax.swing.JButton btluu;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btthoat;
    private javax.swing.JButton btxoa;
    private javax.swing.JComboBox<String> cbkichco;
    private javax.swing.JComboBox<String> cbmausac;
    private javax.swing.JComboBox<String> cbmsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbbienthesanpham;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
