/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.sql.SQLException;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Proccess.ChiTietBanHang;
import java.util.logging.Logger;

public class frmChiTietBanHang extends javax.swing.JFrame {

    private final ChiTietBanHang ctbh = new ChiTietBanHang();
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private int maBanHang;
    private boolean cothem = true;
    private static final Logger logger = Logger.getLogger(frmChiTietBanHang.class.getName());

    public frmChiTietBanHang(int maBanHang) throws SQLException {
        this.maBanHang = maBanHang;
        initComponents();

        tableModel.setColumnIdentifiers(new Object[]{"Mã CT", "Mã SP", "Màu sắc", "Kích cỡ", "Số lượng", "Đơn giá"});
        tblctbh.setModel(tableModel);

        loadMaSP();
        setNull();
        setButton(true);
        setKhoa(true);

        cbmasp.addActionListener(e -> {
            try {
                loadMauSac();
                loadKichCo();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        });

        showData();
    }

    // ===============================
    // Hàm hiển thị dữ liệu
    // ===============================
    public void showData() throws SQLException {
        List<ChiTietBanHang> list = ctbh.getListByMaBanHang(maBanHang);
        tableModel.setRowCount(0);
        for (ChiTietBanHang ctpn : list) {
            Object[] row = new Object[6];
            row[0] = ctpn.getMaBanHangChiTiet();
            row[1] = ctpn.getMaSanPham();
            row[2] = ctbh.getMauSacByBienThe(ctpn.getMaBienThe());
            row[3] = ctbh.getKichCoByBienThe(ctpn.getMaBienThe());
            row[4] = ctpn.getSoLuong();
            row[5] = ctpn.getDonGia();
            tableModel.addRow(row);
        }
    }

    // ===============================
    // Load Mã SP
    // ===============================
    public void loadMaSP() throws SQLException {
        cbmasp.removeAllItems();
        List<Integer> list = ctbh.getListMaSanPham();
        for (Integer masp : list) cbmasp.addItem(masp);
        cbmasp.setSelectedItem(null);
    }

    // ===============================
    // Load màu sắc theo SP
    // ===============================
    public void loadMauSac() throws SQLException {
        if (cbmasp.getSelectedItem() == null) return;
        int masp = (int) cbmasp.getSelectedItem();
        cbmausac.removeAllItems();
        List<String> list = ctbh.getListMauBySanPham(masp);
        for (String mau : list) cbmausac.addItem(mau);
        cbmausac.setSelectedItem(null);
    }

    // ===============================
    // Load kích cỡ theo SP
    // ===============================
    public void loadKichCo() throws SQLException {
        if (cbmasp.getSelectedItem() == null) return;
        int masp = (int) cbmasp.getSelectedItem();
        cbkichco.removeAllItems();
        List<Integer> list = ctbh.getListKichCoBySanPham(masp);
        for (int size : list) cbkichco.addItem(size);
        cbkichco.setSelectedItem(null);
    }

    // ===============================
    // Set null
    // ===============================
    public void setNull() {
        txtSoLuong.setText("");
        txtDonGia.setText("");
        cbmasp.setSelectedItem(null);
        cbmausac.setSelectedItem(null);
        cbkichco.setSelectedItem(null);
    }

    // ===============================
    // Set button
    // ===============================
    public void setButton(boolean a) {
        btnThem.setEnabled(a);
        btnSua.setEnabled(a);
        btnXoa.setEnabled(a);
        btnLuu.setEnabled(!a);
        btnKLuu.setEnabled(!a);
    }

    // ===============================
    // Set khóa
    // ===============================
    public void setKhoa(boolean a) {
        txtSoLuong.setEditable(!a);
        txtDonGia.setEditable(!a);
        cbmasp.setEnabled(!a);
        cbmausac.setEnabled(!a);
        cbkichco.setEnabled(!a);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnKLuu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblctbh = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        txttongtien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtmbhct = new javax.swing.JTextField();
        cbkichco = new javax.swing.JComboBox<>();
        cbmausac = new javax.swing.JComboBox<>();
        cbmasp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Màu sắc");

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã Sản Phẩm");

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnKLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKLuu.setText("KLưu");
        btnKLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Kích cỡ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.textHighlight);
        jLabel9.setText("Chi tiết bán hàng");

        tblctbh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã bán hàng CT", "Mã bán hàng", "Mã SP", "Màu sắc", "Kích cỡ", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblctbh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblctbhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblctbh);
        if (tblctbh.getColumnModel().getColumnCount() > 0) {
            tblctbh.getColumnModel().getColumn(1).setResizable(false);
            tblctbh.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số lượng");

        btnThoat.setBackground(new java.awt.Color(255, 0, 0));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Đơn giá");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tổng tiền");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã Bán Hàng Chi Tiết");

        txtmbhct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmbhctActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addComponent(txtmbhct, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(46, 46, 46)
                        .addComponent(btnSua)
                        .addGap(52, 52, 52)
                        .addComponent(btnXoa)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtDonGia))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(92, 92, 92))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(cbmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbkichco, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbmausac, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLuu)
                                .addGap(71, 71, 71)))
                        .addComponent(btnKLuu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLuu)
                    .addComponent(btnKLuu)
                    .addComponent(btnThoat))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmbhct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbkichco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        setNull();
        setButton(false);
        setKhoa(false);
        cothem = true;
        tblctbh.setEnabled(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tblctbh.getSelectedRow();
        if (row >= 0) {
            setButton(false);
            setKhoa(false);
            cothem = false;
            tblctbh.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để sửa");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tblctbh.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xóa!");
            return;
        }
        int maCT = (int) tblctbh.getValueAt(row, 0);
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa chi tiết này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            ctbh.setMaBanHangChiTiet(maCT);
            if (ctbh.deleteChiTiet()) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                try { showData(); } catch (SQLException e) { e.printStackTrace(); }
                setNull();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if (cbmasp.getSelectedItem() == null || cbmausac.getSelectedItem() == null || cbkichco.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn SP, màu sắc, kích cỡ");
            return;
        }

        int maSP = (int) cbmasp.getSelectedItem();
        String mauSac = (String) cbmausac.getSelectedItem();
        int kichCo = (int) cbkichco.getSelectedItem();
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        double donGia = Double.parseDouble(txtDonGia.getText());

        Integer maBienThe = ctbh.getMaBienThe(maSP, mauSac, kichCo);
        if (maBienThe == null) {
            JOptionPane.showMessageDialog(this, "Biến thể sản phẩm không tồn tại!");
            return;
        }

        ctbh.setMaBanHang(maBanHang);
        ctbh.setMaSanPham(maSP);
        ctbh.setMaBienThe(maBienThe);
        ctbh.setSoLuong(soLuong);
        ctbh.setDonGia(donGia);

        boolean kq;
        if (cothem) kq = ctbh.addChiTiet();
        else kq = ctbh.updateChiTiet();

        if (kq) JOptionPane.showMessageDialog(this, cothem ? "Thêm thành công!" : "Cập nhật thành công!");
        try { showData(); } catch (SQLException e) { e.printStackTrace(); }
        setNull();
        setButton(true);
        setKhoa(true);
        tblctbh.setEnabled(true);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnKLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuActionPerformed
        // TODO add your handling code here:
       setNull();
        setButton(true);
        setKhoa(true);
        tblctbh.setEnabled(true);
    }//GEN-LAST:event_btnKLuuActionPerformed

    private void tblctbhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblctbhMouseClicked
         int row = tblctbh.getSelectedRow();
        if (row < 0) return;

        int maCT = (int) tblctbh.getValueAt(row, 0);
        int maSP = (int) tblctbh.getValueAt(row, 1);
        String mauSac = tblctbh.getValueAt(row, 2).toString();
        int kichCo = (int) tblctbh.getValueAt(row, 3);

        ChiTietBanHang obj = ctbh.getChiTiet(maBanHang, ctbh.getMaBienThe(maSP, mauSac, kichCo));
        if (obj != null) {
            cbmasp.setSelectedItem(obj.getMaSanPham());
            cbmausac.setSelectedItem(mauSac);
            cbkichco.setSelectedItem(kichCo);
            txtSoLuong.setText(String.valueOf(obj.getSoLuong()));
            txtDonGia.setText(String.valueOf(obj.getDonGia()));
        }
    }//GEN-LAST:event_tblctbhMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtmbhctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmbhctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmbhctActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        

    // Chỉ test UI, không chạy thực tế
    java.awt.EventQueue.invokeLater(() -> {
        // Nếu muốn test, truyền một mã bán hàng có tồn tại, ví dụ 1
        // frmChiTietBanHang testFrm = new frmChiTietBanHang(1);
        // testFrm.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuu;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<Integer> cbkichco;
    private javax.swing.JComboBox<Integer> cbmasp;
    private javax.swing.JComboBox<String> cbmausac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblctbh;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtmbhct;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables
}
