/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import Proccess.ChiTietBanHang;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
/**
 *
 * @author Admin
 */
public class frmChiTietBanHang extends javax.swing.JFrame {
    private ChiTietBanHang ctbh = new ChiTietBanHang();
    private DefaultTableModel model;
    private boolean editMode = false; // true khi thêm mới
    private int maBanHang; // Mã bán hàng từ form cha

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmChiTietBanHang.class.getName());

    /**
     * Creates new form frmChiTietBanHang
     */
    public frmChiTietBanHang(int maBanHang) {
        this.maBanHang = maBanHang;
        initComponents();
        model = (DefaultTableModel) tbChiTiet.getModel();
        setButton(true);
        setEnableFields(false);
        loadComboBoxSanPham();
        loadTable();
        addTableListener();
        txtMaCT.setEnabled(false); // Khóa mã chi tiết
    }
    // Load danh sách sản phẩm lên combobox
    

    // ================= Thêm listener cho table =================
    private void addTableListener() {
        tbChiTiet.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (tbChiTiet.getSelectedRow() >= 0) {
                    fillToForm();
                }
            }
        });
    }

    // Load combo sản phẩm
    private void loadComboBoxSanPham() {
        try {
            List<Integer> listSP = ctbh.getListMaSanPham();
            cbMaSP.removeAllItems();
            for (Integer sp : listSP) cbMaSP.addItem(sp.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load sản phẩm: " + e.getMessage());
        }
    }

    private void loadTable() {
        model.setRowCount(0);
        List<ChiTietBanHang> list = ctbh.getListByMaBanHang(maBanHang);
        for (ChiTietBanHang ct : list) {
            model.addRow(new Object[]{
                    ct.getMaBanHangChiTiet(),
                    ct.getMaBanHang(),
                    ct.getMaSanPham(),
                    ct.getSoLuong(),
                    ct.getDonGia()
            });
        }
    }

    private void setEnableFields(boolean enable) {
        cbMaSP.setEnabled(enable);
        txtSoLuong.setEnabled(enable);
        txtDonGia.setEnabled(enable);
    }

    private void setButton(boolean enable) {
        btthem.setEnabled(enable);
        btsua.setEnabled(enable);
        btxoa.setEnabled(enable);
        btluu.setEnabled(!enable);
        btkluu.setEnabled(!enable);
    }

    private void clearInput() {
        txtMaCT.setText("");
        cbMaSP.setSelectedIndex(0);
        txtSoLuong.setText("");
        txtDonGia.setText("");
    }

    private void fillToForm() {
        int row = tbChiTiet.getSelectedRow();
        if (row >= 0) {
            txtMaCT.setText(model.getValueAt(row, 0).toString());
            cbMaSP.setSelectedItem(model.getValueAt(row, 2).toString());
            txtSoLuong.setText(model.getValueAt(row, 3).toString());
            txtDonGia.setText(model.getValueAt(row, 4).toString());
        }
    }

    private boolean validateInput() {
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống!");
            txtSoLuong.requestFocus();
            return false;
        }
        if (txtDonGia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Đơn giá không được để trống!");
            txtDonGia.requestFocus();
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaCT = new javax.swing.JTextField();
        cbMaSP = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        btluu = new javax.swing.JButton();
        btkluu = new javax.swing.JButton();
        btthoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChiTiet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 121, 227));
        jLabel1.setText("Danh sách chi tiết bán hàng");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã bán hàng chi tiết:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mã bán hàng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã sản phẩm:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Số lượng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Đơn giá:");

        btthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btxoa.setText("Xóa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        btluu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btluu.setText("Lưu");
        btluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuActionPerformed(evt);
            }
        });

        btkluu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btkluu.setText("K.Lưu");
        btkluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkluuActionPerformed(evt);
            }
        });

        btthoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btthoat.setText("Thoát");
        btthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthoatActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        tbChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã bán hàng chi tiết", "Mã bán hàng", "Mã sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbChiTiet);
        if (tbChiTiet.getColumnModel().getColumnCount() > 0) {
            tbChiTiet.getColumnModel().getColumn(0).setResizable(false);
            tbChiTiet.getColumnModel().getColumn(1).setResizable(false);
            tbChiTiet.getColumnModel().getColumn(2).setResizable(false);
            tbChiTiet.getColumnModel().getColumn(3).setResizable(false);
            tbChiTiet.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaCT)
                                    .addComponent(cbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btthem)
                                .addGap(30, 30, 30)
                                .addComponent(btsua)
                                .addGap(30, 30, 30)
                                .addComponent(btxoa)
                                .addGap(31, 31, 31)
                                .addComponent(btluu)
                                .addGap(37, 37, 37)
                                .addComponent(btkluu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 116, Short.MAX_VALUE)
                            .addComponent(txtSoLuong)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btthoat)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtMaCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(cbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(btsua)
                    .addComponent(btxoa)
                    .addComponent(btluu)
                    .addComponent(btkluu)
                    .addComponent(btthoat))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        clearInput();
        setEnableFields(true);
        setButton(false);
        editMode = true;
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        int row = tbChiTiet.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn chi tiết để sửa!");
            return;
        }
        setEnableFields(true);
        setButton(false);
        editMode = false;
    }//GEN-LAST:event_btsuaActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        int row = tbChiTiet.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn chi tiết để xóa!");
            return;
        }

        Object value = tbChiTiet.getValueAt(row, 0);
        if (value == null || value.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã chi tiết không hợp lệ!");
            return;
        }

        try {
            int id = Integer.parseInt(value.toString());
            ctbh.setMaBanHangChiTiet(id);

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc muốn xóa chi tiết này?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) return;

            if (ctbh.deleteChiTiet()) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadTable();
                clearInput();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mã chi tiết không hợp lệ: " + ex.getMessage());
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        // TODO add your handling code here:
        if (!validateInput()) return;

        ctbh.setMaBanHang(maBanHang);
        ctbh.setMaSanPham(Integer.parseInt(cbMaSP.getSelectedItem().toString()));
        ctbh.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        ctbh.setDonGia(Double.parseDouble(txtDonGia.getText()));

        boolean success;
        if (editMode) {
            // Thêm mới: CSDL tự tăng MaBanHangChiTiet
            success = ctbh.addChiTiet();
        } else {
            // Sửa: lấy từ bảng
            int row = tbChiTiet.getSelectedRow();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Chọn chi tiết để sửa!");
                return;
            }
            Object value = tbChiTiet.getValueAt(row, 0);
            ctbh.setMaBanHangChiTiet(Integer.parseInt(value.toString()));
            success = ctbh.updateChiTiet();
        }

        if (success) {
            JOptionPane.showMessageDialog(this, "Lưu thành công!");
            loadTable();
            clearInput();
            setButton(true);
            setEnableFields(false);
            editMode = false;
        } else {
            JOptionPane.showMessageDialog(this, "Lưu thất bại!");
        }
    }//GEN-LAST:event_btluuActionPerformed

    private void btkluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkluuActionPerformed
        // TODO add your handling code here:
        clearInput();
        setButton(true);
        setEnableFields(false);
        editMode = false;
    }//GEN-LAST:event_btkluuActionPerformed

    private void btthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthoatActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        

    // Chỉ test UI, không chạy thực tế
    java.awt.EventQueue.invokeLater(() -> {
        // Nếu muốn test, truyền một mã bán hàng có tồn tại, ví dụ 1
        // frmChiTietBanHang testFrm = new frmChiTietBanHang(1);
        // testFrm.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btkluu;
    private javax.swing.JButton btluu;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btthoat;
    private javax.swing.JButton btxoa;
    private javax.swing.JComboBox<String> cbMaSP;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbChiTiet;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaCT;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
