/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Proccess.ChiTietMuaHang;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */

public class frmChiTietMuaHang extends javax.swing.JFrame {

    private final ChiTietMuaHang ct = new ChiTietMuaHang();
    private boolean cothem = false;
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private int maMHselected = -1; // nếu khác -1 => form được mở theo mã mua hàng và cbMaMH sẽ bị khóa

    // Constructor mặc định
    public frmChiTietMuaHang() {
        initComponents();
        initForm();
    }

    // Constructor khi mở từ frmMuaHang với MaMuaHang cụ thể
    public frmChiTietMuaHang(int maMHselected) {
        this.maMHselected = maMHselected;
        initComponents();
        initForm();
    }

    // Khởi tạo form: thiết lập table model, nạp combo, show data, set trạng thái button
    private void initForm() {
        tableModel.setColumnIdentifiers(new Object[]{"Mã mua hàng", "Mã sản phẩm", "Số lượng", "Đơn giá"});
        tblCTMH.setModel(tableModel);

        loadComboBoxMaMH();
        loadComboBoxMaSP();

        // Nếu form được mở theo maMHselected, chọn item đó và khóa combo để tránh sửa mã mua hàng
        if (maMHselected != -1) {
            String key = String.valueOf(maMHselected);
            boolean found = false;
            for (int i = 0; i < cbMaMH.getItemCount(); i++) {
                if (key.equals(cbMaMH.getItemAt(i))) {
                    found = true;
                    break;
                }
            }
            if (found) {
                cbMaMH.setSelectedItem(key);
                cbMaMH.setEnabled(false);
            }
        }

        setNull();
        setButton(true);
        setKhoa(true);
        showData();
    }

    private void loadComboBoxMaMH() {
        try {
            cbMaMH.removeAllItems();
            List<Integer> list = ct.getAllMaMH();
            for (Integer x : list) cbMaMH.addItem(String.valueOf(x));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nạp MaMuaHang: " + e.getMessage());
        }
    }

    private void loadComboBoxMaSP() {
        try {
            cbMaSP.removeAllItems();
            List<Integer> list = ct.getAllMaSP();
            for (Integer x : list) cbMaSP.addItem(String.valueOf(x));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nạp MaSanPham: " + e.getMessage());
        }
    }

    private void setNull() {
        // Nếu cbMaMH đã bị khóa (do maMHselected), không đổi cbMaMH
        if (maMHselected == -1) cbMaMH.setSelectedItem(null);
        cbMaSP.setSelectedItem(null);
        txtSoluong.setText("");
        txtDongia.setText("");
    }

    private void setButton(boolean a) {
        btnThemCTMH.setEnabled(a);
        btnSuaCTMH.setEnabled(a);
        btnXoaCTMH.setEnabled(a);
        btnLuuCTMH.setEnabled(!a);
        btnKLuuCTMH.setEnabled(!a);
    }

    private void setKhoa(boolean a) {
        // Nếu form đang mở theo maMHselected thì cbMaMH luôn khóa (không được thay đổi)
        cbMaMH.setEnabled(maMHselected == -1 && !a);
        cbMaSP.setEnabled(!a);
        txtSoluong.setEditable(!a);
        txtDongia.setEditable(!a);
    }

    private void showData() {
        tableModel.setRowCount(0);
        try {
            List<ChiTietMuaHang> list;
            if (maMHselected != -1) {
                list = ct.getByMaMuaHang(maMHselected);
            } else {
                list = ct.getAll();
            }
            for (ChiTietMuaHang c : list) {
                tableModel.addRow(new Object[]{c.getMaMH(), c.getMaSP(), c.getSoLuong(), c.getDonGia()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi hiển thị dữ liệu: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThemCTMH = new javax.swing.JButton();
        btnSuaCTMH = new javax.swing.JButton();
        btnXoaCTMH = new javax.swing.JButton();
        btnLuuCTMH = new javax.swing.JButton();
        btnKLuuCTMH = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMaMH = new javax.swing.JComboBox<>();
        cbMaSP = new javax.swing.JComboBox<>();
        txtSoluong = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTMH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT MUA HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        btnThemCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemCTMH.setText("Thêm");
        btnThemCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTMHActionPerformed(evt);
            }
        });

        btnSuaCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaCTMH.setText("Sửa");
        btnSuaCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCTMHActionPerformed(evt);
            }
        });

        btnXoaCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaCTMH.setText("Xóa");
        btnXoaCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTMHActionPerformed(evt);
            }
        });

        btnLuuCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLuuCTMH.setText("Lưu");
        btnLuuCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCTMHActionPerformed(evt);
            }
        });

        btnKLuuCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKLuuCTMH.setText("K.Lưu");
        btnKLuuCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuCTMHActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã mua hàng:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Số lượng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Đơn giá:");

        tblCTMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã mua hàng", "Mã sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTMHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTMH);
        if (tblCTMH.getColumnModel().getColumnCount() > 0) {
            tblCTMH.getColumnModel().getColumn(0).setResizable(false);
            tblCTMH.getColumnModel().getColumn(1).setResizable(false);
            tblCTMH.getColumnModel().getColumn(2).setResizable(false);
            tblCTMH.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemCTMH)
                        .addGap(28, 28, 28)
                        .addComponent(btnSuaCTMH)
                        .addGap(28, 28, 28)
                        .addComponent(btnXoaCTMH)
                        .addGap(30, 30, 30)
                        .addComponent(btnLuuCTMH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKLuuCTMH)
                        .addGap(37, 37, 37)
                        .addComponent(btnThoat)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbMaSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(128, 128, 128)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemCTMH)
                    .addComponent(btnSuaCTMH)
                    .addComponent(btnXoaCTMH)
                    .addComponent(btnLuuCTMH)
                    .addComponent(btnKLuuCTMH)
                    .addComponent(btnThoat))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(cbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTMHMouseClicked
        // TODO add your handling code here:                                    
        try {
            int row = tblCTMH.getSelectedRow();
            if (row >= 0) {
                cbMaMH.setSelectedItem(tblCTMH.getValueAt(row, 0).toString());
                cbMaSP.setSelectedItem(tblCTMH.getValueAt(row, 1).toString());
                txtSoluong.setText(tblCTMH.getValueAt(row, 2).toString());
                txtDongia.setText(tblCTMH.getValueAt(row, 3).toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi lấy dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_tblCTMHMouseClicked

    private void btnThemCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTMHActionPerformed
        // TODO add your handling code here:
        setNull();
        setButton(false);
        setKhoa(false);
        cothem = true;
    }//GEN-LAST:event_btnThemCTMHActionPerformed

    private void btnSuaCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCTMHActionPerformed
        // TODO add your handling code here:
        if (cbMaMH.getSelectedItem() == null || cbMaSP.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Hãy chọn chi tiết cần sửa!");
            return;
        }
        setButton(false);
        setKhoa(false);
        cothem = false;
    }//GEN-LAST:event_btnSuaCTMHActionPerformed

    private void btnXoaCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTMHActionPerformed
        // TODO add your handling code here:
         if (cbMaMH.getSelectedItem() == null || cbMaSP.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Hãy chọn chi tiết cần xóa!");
            return;
        }
        int maMH = Integer.parseInt(cbMaMH.getSelectedItem().toString());
        int maSP = Integer.parseInt(cbMaSP.getSelectedItem().toString());

        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xóa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (ct.deleteData(maMH, maSP)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                showData();
                setNull();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btnXoaCTMHActionPerformed

    private void btnLuuCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCTMHActionPerformed
        // TODO add your handling code here:
         if (cbMaMH.getSelectedItem() == null || cbMaSP.getSelectedItem() == null ||
                txtSoluong.getText().isEmpty() || txtDongia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        try {
            int maMH = Integer.parseInt(cbMaMH.getSelectedItem().toString());
            int maSP = Integer.parseInt(cbMaSP.getSelectedItem().toString());
            int sl = Integer.parseInt(txtSoluong.getText().trim());
            double dg = Double.parseDouble(txtDongia.getText().trim());

            ChiTietMuaHang obj = new ChiTietMuaHang();
            obj.setMaMH(maMH);
            obj.setMaSP(maSP);
            obj.setSoLuong(sl);
            obj.setDonGia(dg);

            boolean ok = cothem ? ct.insertData(obj) : ct.editData(obj);

            if (ok) {
                JOptionPane.showMessageDialog(this, (cothem ? "Thêm" : "Sửa") + " thành công!");
                showData();
                setNull();
                setButton(true);
                setKhoa(true);
            } else {
                JOptionPane.showMessageDialog(this, (cothem ? "Thêm" : "Sửa") + " thất bại!");
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Số lượng/Đơn giá phải là số!");
        }
    }//GEN-LAST:event_btnLuuCTMHActionPerformed

    private void btnKLuuCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuCTMHActionPerformed
        // TODO add your handling code here:
        setNull();
        setButton(true);
        setKhoa(true);
        tblCTMH.setEnabled(true);
    }//GEN-LAST:event_btnKLuuCTMHActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        frmChiTietMuaHang fr = new frmChiTietMuaHang();
        fr.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuCTMH;
    private javax.swing.JButton btnLuuCTMH;
    private javax.swing.JButton btnSuaCTMH;
    private javax.swing.JButton btnThemCTMH;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaCTMH;
    private javax.swing.JComboBox<String> cbMaMH;
    private javax.swing.JComboBox<String> cbMaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCTMH;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtSoluong;
    // End of variables declaration//GEN-END:variables
}
