/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Proccess.ChiTietPhieuXuat;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngocanh
 */
public class frmChiTietPhieuXuat extends javax.swing.JFrame {
    private final ChiTietPhieuXuat ct = new ChiTietPhieuXuat();
    private final DefaultTableModel tableModel= new DefaultTableModel();
    private int maPX;
    private boolean cothem=true;
    public void ShowData() throws SQLException{
        List<ChiTietPhieuXuat> list = ct.getall(maPX);
        tableModel.setRowCount(0);
        for(ChiTietPhieuXuat ctpn:list){
            Object[] row = new Object[7];
            row[0]= ctpn.getMaSP();
            row[1]=ctpn.getTenSP();
            row[2]=ctpn.getMauSac();
            row[3]=ctpn.getKichCo();
            row[4]=ctpn.getSoLuong();
            row[5]=ctpn.getDonGia();

            tableModel.addRow(row);
        }
    }
    public void loadMaSp() throws SQLException{
        cbMaSP.removeAllItems();
        List<Integer> list = ct.getallMasp();
        for (Integer masp:list){
            cbMaSP.addItem(masp);
        }
        cbMaSP.setSelectedItem(null);
    }
    public void loadtensp() throws SQLException{
        if (cbMaSP.getSelectedItem() == null) return;
        int masp = Integer.parseInt(cbMaSP.getSelectedItem().toString());
        txtTenSP.setText(ct.setTensp(masp));
    }
    public void loadmausac() throws SQLException{
        if (cbMaSP.getSelectedItem() == null) return;
        cbMauSac.removeAllItems();
        int masp = Integer.parseInt(cbMaSP.getSelectedItem().toString());
        List<String> mausac = ct.getallmausac(masp);
        for(String a:mausac){
            cbMauSac.addItem(a);
        }
    }
    public void loadkichco() throws SQLException{
        if (cbMaSP.getSelectedItem() == null) return;
        cbKichCo.removeAllItems();
        int masp = Integer.parseInt(cbMaSP.getSelectedItem().toString());
        List<Integer> kichco = ct.getallkichco(masp);
        for(int a:kichco){
            cbKichCo.addItem(a);
        }
    }
    public void setnull(){
        txtDonGia.setText("");
        txtSoLuong.setText("");
        txtTenSP.setText("");
        cbKichCo.setSelectedItem(null);
        cbMaSP.setSelectedItem(null);
        cbMauSac.setSelectedItem(null);
    }
    public void setbutton(boolean a){
        btnThemCTPX.setEnabled(a);
        btnSuaCTPX.setEnabled(a);
        btnXoaCTPX.setEnabled(a);
        btnLuuCTPX.setEnabled(!a);
        btnKLuuCTPX.setEnabled(!a);
        
    }
    public void setKhoa(boolean a){
        txtDonGia.setEditable(!a);
        txtSoLuong.setEditable(!a);
        cbKichCo.setEnabled(!a);
        cbMaSP.setEnabled(!a); 
        cbMauSac.setEnabled(!a); 
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmChiTietPhieuXuat.class.getName());

    /**
     * Creates new form ChiTietPhieuXuat
     */
    public frmChiTietPhieuXuat(int mapx) throws SQLException{
        this.maPX = mapx;
        initComponents();
        tableModel.setColumnIdentifiers(new Object[]{"MaSP","TenSP","Màu sắc","Kích cỡ","Số lượng","Đơn giá"});
        tblCTPX.setModel(tableModel);
        loadMaSp();
        setnull();
        setbutton(true);
        setKhoa(true);
        cbMaSP.addActionListener(e -> {
            try {
                loadtensp(); 
                loadmausac();
                loadkichco();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        });
        ShowData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMauSac = new javax.swing.JComboBox<>();
        btnKLuuCTPX = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbKichCo = new javax.swing.JComboBox<>();
        txtTenSP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        btnThemCTPX = new javax.swing.JButton();
        btnSuaCTPX = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTPX = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbMaSP = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnXoaCTPX = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLuuCTPX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKLuuCTPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKLuuCTPX.setText("KLưu");
        btnKLuuCTPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuCTPXActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Kích cỡ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.textHighlight);
        jLabel9.setText("Chi tiết phiếu xuất");

        txtTenSP.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số lượng");

        btnThoat.setBackground(new java.awt.Color(255, 0, 0));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Đơn giá");

        btnThemCTPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemCTPX.setText("Thêm");
        btnThemCTPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTPXActionPerformed(evt);
            }
        });

        btnSuaCTPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaCTPX.setText("Sửa");
        btnSuaCTPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCTPXActionPerformed(evt);
            }
        });

        tblCTPX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Màu sắc", "Kích cỡ", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCTPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTPXMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTPX);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tổng tiền");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã SP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên SP");

        btnXoaCTPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaCTPX.setText("Xóa");
        btnXoaCTPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTPXActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Màu sắc");

        btnLuuCTPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuCTPX.setText("Lưu");
        btnLuuCTPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCTPXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbMauSac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMaSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbKichCo, 0, 145, Short.MAX_VALUE)
                            .addComponent(txtTenSP))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemCTPX)
                        .addGap(46, 46, 46)
                        .addComponent(btnSuaCTPX)
                        .addGap(52, 52, 52)
                        .addComponent(btnXoaCTPX)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtDonGia))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(92, 92, 92))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLuuCTPX)
                                .addGap(71, 71, 71)))
                        .addComponent(btnKLuuCTPX)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemCTPX)
                    .addComponent(btnSuaCTPX)
                    .addComponent(btnXoaCTPX)
                    .addComponent(btnLuuCTPX)
                    .addComponent(btnKLuuCTPX)
                    .addComponent(btnThoat))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKLuuCTPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuCTPXActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(true);
        setKhoa(true);
        tblCTPX.setEnabled(true);
    }//GEN-LAST:event_btnKLuuCTPXActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemCTPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTPXActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(false);
        setKhoa(false);
        cothem=true;
        tblCTPX.setEnabled(false);
    }//GEN-LAST:event_btnThemCTPXActionPerformed

    private void btnSuaCTPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCTPXActionPerformed
        // TODO add your handling code here:
        int row = tblCTPX.getSelectedRow();
        if (row >= 0) {
            setbutton(false);
            setKhoa(false);
            cothem = false;
            tblCTPX.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để sửa");
        }
    }//GEN-LAST:event_btnSuaCTPXActionPerformed

    private void tblCTPXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTPXMouseClicked
        try {
            // TODO add your handling code here:
            int row =tblCTPX.getSelectedRow();
            if(row < 0) return;
            String ma = tblCTPX.getValueAt(row,0).toString();
            int masp=Integer.parseInt(ma);
            String mausac = tblCTPX.getValueAt(row, 2).toString();
            String kt=tblCTPX.getValueAt(row,3).toString();
            int kichco=Integer.parseInt(kt);
            int mabt=ct.getMaBienThe(masp, mausac, kichco);
            ChiTietPhieuXuat obj=ct.getCTPN(maPX,mabt);
            if(obj!=null){
                cbMaSP.setSelectedItem(obj.getMaSP());
                txtDonGia.setText(String.valueOf(obj.getDonGia()));
                txtSoLuong.setText(String.valueOf(obj.getSoLuong()));
                txtTenSP.setText(obj.getTenSP());
                cbKichCo.setSelectedItem(obj.getKichCo());

                cbMauSac.setSelectedItem(obj.getMauSac());
            }
        } catch (SQLException ex) {
            System.getLogger(frmChiTietPhieuXuat.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_tblCTPXMouseClicked

    private void btnXoaCTPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTPXActionPerformed
        // TODO add your handling code here:
        int row = tblCTPX.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xóa!");
            return;
        }
        try {
            int maSP = (int) tblCTPX.getValueAt(row, 0);
            String mausac = (String) tblCTPX.getValueAt(row, 2);
            int kichco = (int) tblCTPX.getValueAt(row, 3);
            Integer maBienThe = ct.getMaBienThe(maSP, mausac, kichco);
            if(maBienThe == null){
                JOptionPane.showMessageDialog(this, "Biến thể sản phẩm không tồn tại!");
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa chi tiết sản phẩm này?",
                "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION){
                boolean kq = ct.deleteCTPN(maPX, maBienThe);
                if(kq){
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    ShowData();
                    setnull();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                }
            }
        } catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnXoaCTPXActionPerformed

    private void btnLuuCTPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCTPXActionPerformed
        // TODO add your handling code here:
        try {
            int maSP = (int) cbMaSP.getSelectedItem();
            String mausac = (String) cbMauSac.getSelectedItem();
            int kichco = (int) cbKichCo.getSelectedItem();
            int soluong = Integer.parseInt(txtSoLuong.getText());
            float dongia = Float.parseFloat(txtDonGia.getText());
            if (cbMaSP.getSelectedItem() == null || cbMauSac.getSelectedItem() == null || cbKichCo.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ Mã SP, Màu sắc và Kích cỡ!");
                return;
            }
            boolean kq;
            if (cothem) {
                kq = ct.addCTPN(maPX, maSP, mausac, kichco, soluong, dongia);
                if (kq) {
                    tableModel.setRowCount(0); // xóa bảng cũ
                    ShowData(); // load lại dữ liệu
                    setnull();
                    setbutton(true);
                    setKhoa(true);
                    tblCTPX.setEnabled(true);
                }
            } else {
                kq = ct.updateCTPN(maPX, maSP, mausac, kichco, soluong, dongia);
                if (kq) {
                    tableModel.setRowCount(0);
                    ShowData();
                    setnull();
                    setbutton(true);
                    setKhoa(true);
                    tblCTPX.setEnabled(true);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ cho Số lượng, Đơn giá");
        }
    }//GEN-LAST:event_btnLuuCTPXActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuCTPX;
    private javax.swing.JButton btnLuuCTPX;
    private javax.swing.JButton btnSuaCTPX;
    private javax.swing.JButton btnThemCTPX;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaCTPX;
    private javax.swing.JComboBox<Integer> cbKichCo;
    private javax.swing.JComboBox<Integer> cbMaSP;
    private javax.swing.JComboBox<String> cbMauSac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblCTPX;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
