/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.sql.*;
import Proccess.PhieuNhap;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngocanh
 */
public class frmPhieuNhap extends javax.swing.JFrame {
    private final PhieuNhap pn= new PhieuNhap();
    private boolean cothem = false;   
    private final DefaultTableModel tableModel= new DefaultTableModel();
    
    public void loadComboBoxMaNCC() {
        try {
            cbMaNCC.removeAllItems();
            List<Integer> list = pn.getAllNCC(); 
            for (Integer maNCC : list) {
                cbMaNCC.addItem(maNCC);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nạp danh sách NCC: " + e.getMessage());
        }
    }
    public void loadMANv(){
        try {
            cbMaNV.removeAllItems();
            List<Integer> list = pn.getAllMNV();
            for(Integer manv:list){
                cbMaNV.addItem(manv);
            }
        } catch (SQLException ex) {
            System.getLogger(frmPhieuNhap.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    public void setnull(){
        txtGhiChu.setText("");
        txtMaPN.setText("");
        txtNgayNhap.setText("");
        cbMaNCC.setSelectedItem(null);
        cbMaNV.setSelectedItem(null);
    }
    public void setbutton(boolean a){
        btnThemPN.setEnabled(a);
        btnSuaPN.setEnabled(a);
        btnXoaPN.setEnabled(a);
        btnLuuPN.setEnabled(!a);
        btnKLuuPN.setEnabled(!a);
        
    }
    public void setKhoa(boolean a){
        txtGhiChu.setEditable(!a);
        cbMaNCC.setEnabled(!a);
        cbMaNV.setEnabled(!a);
    }
    public void ShowData() throws SQLException{
        List<PhieuNhap> list = pn.getAll(); 
        for(PhieuNhap phieu:list){
            Object[] row = new Object[6];
            row[0] = phieu.getMaPhieuNhap();
            row[1] = phieu.getNgayNhap();
            row[2]=phieu.getMaNCC();
            row[3]=phieu.getMaNV();
            row[4]=phieu.getTongTien();
            row[5]=phieu.getGhiChu();     
            tableModel.addRow(row);
        }
    }
    public void ClearData() throws SQLException{
        int n=tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--){
            tableModel.removeRow(i);
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPhieuNhap.class.getName());

    /**
     * Creates new form frmKho
     */
    public frmPhieuNhap() throws SQLException {
        initComponents();
        tableModel.setColumnIdentifiers(new Object[]{"Mã phiếu nhập", "Ngày nhập", "Mã NCC", "Mã NV", "Tổng tiền", "Ghi chú"});
        tblPN.setModel(tableModel);
        loadMANv();
        loadComboBoxMaNCC();
        ShowData();
        setnull();
        setbutton(true);
        setKhoa(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPN = new javax.swing.JTable();
        btnThemPN = new javax.swing.JButton();
        btnSuaPN = new javax.swing.JButton();
        btnXoaPN = new javax.swing.JButton();
        btnLuuPN = new javax.swing.JButton();
        btnKLuuPN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbMaNCC = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 255, 102)), "Danh sách phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), java.awt.SystemColor.textHighlight)); // NOI18N

        tblPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Ngày nhập", "Mã NCC", "Mã NV", "Tổng tiền", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPN);

        btnThemPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemPN.setText("Thêm");
        btnThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPNActionPerformed(evt);
            }
        });

        btnSuaPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaPN.setText("Sửa");
        btnSuaPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPNActionPerformed(evt);
            }
        });

        btnXoaPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaPN.setText("Xóa");
        btnXoaPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPNActionPerformed(evt);
            }
        });

        btnLuuPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuPN.setText("Lưu");
        btnLuuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPNActionPerformed(evt);
            }
        });

        btnKLuuPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKLuuPN.setText("Klưu");
        btnKLuuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuPNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã phiếu nhập");

        txtMaPN.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ngày nhập");

        txtNgayNhap.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã NCC");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã NV");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemPN)
                        .addGap(24, 24, 24)
                        .addComponent(btnSuaPN)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaPN)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuuPN)
                        .addGap(18, 18, 18)
                        .addComponent(btnKLuuPN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbMaNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(198, 198, 198)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(61, 61, 61)
                                        .addComponent(cbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemPN)
                    .addComponent(btnSuaPN)
                    .addComponent(btnXoaPN)
                    .addComponent(btnLuuPN)
                    .addComponent(btnKLuuPN))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPNMouseClicked
        try {
            // TODO add your handling code here:
            int row=tblPN.getSelectedRow();
            String ma=tblPN.getValueAt(row,0).toString();
            PhieuNhap obj=pn.getPhieuNhap(ma);
            if(obj!=null){
                txtGhiChu.setText(obj.getGhiChu());
                txtMaPN.setText(String.valueOf(obj.getMaPhieuNhap()));
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                txtNgayNhap.setText(sdf.format(obj.getNgayNhap()));
                cbMaNCC.setSelectedItem(obj.getMaNCC());
                cbMaNV.setSelectedItem(obj.getMaNV());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + ex.getMessage());
        }
    }//GEN-LAST:event_tblPNMouseClicked

    private void btnXoaPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPNActionPerformed
        // TODO add your handling code here:
        String ma=txtMaPN.getText();
        try{
            if(ma.isEmpty()){
                JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần xóa!");
                return;
            }
            int mpn=Integer.parseInt(ma);
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa không!")==JOptionPane.YES_OPTION){
                pn.deleteData(mpn); 
                ClearData();
                ShowData();
                setnull();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaPNActionPerformed

    private void btnThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPNActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(false);
        setKhoa(false);
        cothem=true; 
        tblPN.setEnabled(false);
        
    }//GEN-LAST:event_btnThemPNActionPerformed

    private void btnLuuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPNActionPerformed
        // TODO add your handling code here:
        Object manccObj = cbMaNCC.getSelectedItem();
        Object manvObj = cbMaNV.getSelectedItem();
        String ghichu = txtGhiChu.getText().trim();
        String mapn=txtMaPN.getText();

        if(manccObj == null || manvObj == null){
            JOptionPane.showMessageDialog(this,"Vui lòng điền đầy đủ thông tin!");
        }
        
        else{
            try {
            int mancc = (int) manccObj;
            int manv = (int) manvObj;
            int maphieunhap = Integer.parseInt(mapn);
            PhieuNhap obj = new PhieuNhap();
            java.util.Date now = new java.util.Date();
            obj.setNgayNhap(now);   // tự động lấy thời gian hiện tại
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
//            txtNgayNhap.setText(sdf.format(now));
            obj.setMaNCC(mancc);
            obj.setMaNV(manv);
            obj.setTongTien(0); // mặc định 0 khi mới nhập
            obj.setGhiChu(ghichu);
            obj.setMaPhieuNhap(maphieunhap);
            if(cothem==true){
                pn.InsertData(obj);
            }
            else{
                pn.EditData(obj);
            }
            ClearData();
            ShowData();
            setnull();
            setbutton(true);
            setKhoa(true);
            cothem=false;
            tblPN.setEnabled(true);
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Cập nhật thất bại");
            }
        }
    }//GEN-LAST:event_btnLuuPNActionPerformed

    private void btnSuaPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPNActionPerformed
        // TODO add your handling code here:
        String mapn=txtMaPN.getText();
        if(mapn.isEmpty()){
            JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần sửa!");
        }
        else{
            setKhoa(false);
            tblPN.setEnabled(false);
            setbutton(false);
            cothem=false;
        }
    }//GEN-LAST:event_btnSuaPNActionPerformed

    private void btnKLuuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuPNActionPerformed
        // TODO add your handling code here:
        setnull();
        setKhoa(true);
        setbutton(true);
    }//GEN-LAST:event_btnKLuuPNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        frmPhieuNhap fr=new frmPhieuNhap();
        fr.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuPN;
    private javax.swing.JButton btnLuuPN;
    private javax.swing.JButton btnSuaPN;
    private javax.swing.JButton btnThemPN;
    private javax.swing.JButton btnXoaPN;
    private javax.swing.JComboBox<Integer> cbMaNCC;
    private javax.swing.JComboBox<Integer> cbMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPN;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtNgayNhap;
    // End of variables declaration//GEN-END:variables
}
