/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Proccess.ChiTietMuaHang;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */

public class panelChiTietMuaHang extends javax.swing.JPanel {

    private final ChiTietMuaHang ct = new ChiTietMuaHang();
    private boolean cothem = false;

    private final DefaultTableModel tableModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // khóa chỉnh sửa trực tiếp
        }
    };

    public panelChiTietMuaHang() {
        initComponents();
        tblCTMH.setModel(tableModel);
        initForm();

        tblCTMH.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCTMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTMHMouseClicked(evt);
            }
        });
    }

    private void initForm() {
        tableModel.setColumnIdentifiers(new Object[]{"Mã SP","Tên SP","Màu sắc","Kích cỡ","Số lượng","Đơn giá"});
        loadComboBoxMaSP();
        setNull();
        setButton(true);
        setKhoa(true);
        showData();
    }

    private void loadComboBoxMaSP() {
        cbMaSP.removeAllItems();
        List<Integer> list = ct.getAllMaSP();
        for (Integer maSP : list) cbMaSP.addItem(String.valueOf(maSP));
    }

    private void loadComboBoxMauSac(int maSP) {
        cbms.removeAllItems();
        List<String> list = ct.getAllMauSac(maSP);
        for (String s : list) cbms.addItem(s);
    }

    private void loadComboBoxKichCo(int maSP) {
        cbkt.removeAllItems();
        List<Integer> list = ct.getAllKichCo(maSP);
        for (Integer x : list) cbkt.addItem(String.valueOf(x));
    }

    private void setNull() {
        cbMaSP.setSelectedItem(null);
        cbms.removeAllItems();
        cbkt.removeAllItems();
        txtSoluong.setText("");
        txtDongia.setText("");
        txtTensp.setText("");
    }

    private void setButton(boolean a) {
        btnThemCTMH.setEnabled(a);
        btnSuaCTMH.setEnabled(a);
        btnXoaCTMH.setEnabled(a);
        btnLuuCTMH.setEnabled(!a);
        btnKLuuCTMH.setEnabled(!a);
    }

    private void setKhoa(boolean a) {
        cbMaSP.setEnabled(!a);
        cbms.setEnabled(!a);
        cbkt.setEnabled(!a);
        txtSoluong.setEditable(!a);
        txtDongia.setEditable(!a);
    }

    private void showData() {
        tableModel.setRowCount(0);
        List<ChiTietMuaHang> list = ct.getAll();
        if (list != null) {
            for (ChiTietMuaHang c : list) {
                tableModel.addRow(new Object[]{
                        c.getMaSP(),
                        c.getTenSP(),
                        c.getMauSac(),
                        c.getKichCo(),
                        c.getSoLuong(),
                        c.getDonGia()
                });
            }
        }
    }
    public void loadDataByMaMH(int maMH) {
        tableModel.setRowCount(0); // xóa dữ liệu cũ
        List<ChiTietMuaHang> list = ct.getByMaMH(maMH); 
        if (list != null) {
            for (ChiTietMuaHang c : list) {
                tableModel.addRow(new Object[]{
                    c.getMaSP(), c.getTenSP(), c.getMauSac(),
                    c.getKichCo(), c.getSoLuong(), c.getDonGia()
                });
            }
        }
    }

    // Getter cho JTable
    public JTable getTblCTMH() {
        return tblCTMH;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThemCTMH = new javax.swing.JButton();
        btnSuaCTMH = new javax.swing.JButton();
        btnXoaCTMH = new javax.swing.JButton();
        btnLuuCTMH = new javax.swing.JButton();
        btnKLuuCTMH = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMaSP = new javax.swing.JComboBox<>();
        txtSoluong = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTMH = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbkt = new javax.swing.JComboBox<>();
        cbms = new javax.swing.JComboBox<>();
        txtTensp = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT MUA HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        btnThemCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemCTMH.setText("Thêm");
        btnThemCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTMHActionPerformed(evt);
            }
        });

        btnSuaCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaCTMH.setText("Sửa");
        btnSuaCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCTMHActionPerformed(evt);
            }
        });

        btnXoaCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaCTMH.setText("Xóa");
        btnXoaCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTMHActionPerformed(evt);
            }
        });

        btnLuuCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLuuCTMH.setText("Lưu");
        btnLuuCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuCTMHActionPerformed(evt);
            }
        });

        btnKLuuCTMH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKLuuCTMH.setText("K.Lưu");
        btnKLuuCTMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuCTMHActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tên sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Số lượng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Đơn giá:");

        cbMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaSPActionPerformed(evt);
            }
        });

        tblCTMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Màu sắc", "Kích cỡ", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTMHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTMH);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kích cỡ:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Màu sắc:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbms, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbkt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThemCTMH)
                                .addGap(208, 208, 208)
                                .addComponent(btnXoaCTMH))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSuaCTMH)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuCTMH)
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThoat)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnKLuuCTMH)
                                .addGap(341, 341, 341))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemCTMH)
                    .addComponent(btnSuaCTMH)
                    .addComponent(btnXoaCTMH)
                    .addComponent(btnLuuCTMH)
                    .addComponent(btnKLuuCTMH)
                    .addComponent(btnThoat))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(cbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTMHActionPerformed
        // TODO add your handling code here:
        setNull();
        setButton(false);
        setKhoa(false);
        cothem = true;
    }//GEN-LAST:event_btnThemCTMHActionPerformed

    private void btnSuaCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCTMHActionPerformed
        // TODO add your handling code here:
        if (cbMaSP.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Hãy chọn chi tiết cần sửa!");
            return;
        }
        setButton(false);
        setKhoa(false);
        cothem = false;
    }//GEN-LAST:event_btnSuaCTMHActionPerformed

    private void btnXoaCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTMHActionPerformed
        // TODO add your handling code here:
        if (cbMaSP.getSelectedItem() == null || cbms.getSelectedItem() == null || cbkt.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Hãy chọn chi tiết cần xóa!");
            return;
        }
        try {
            int maSP = Integer.parseInt(cbMaSP.getSelectedItem().toString());
            String mausac = cbms.getSelectedItem().toString();
            int kichco = Integer.parseInt(cbkt.getSelectedItem().toString());

            if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xóa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (ct.deleteChiTiet(maSP, mausac, kichco)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    showData();
                    setNull();
                } else JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa: " + e.getMessage());
        }
    }//GEN-LAST:event_btnXoaCTMHActionPerformed

    private void btnLuuCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuCTMHActionPerformed
        // TODO add your handling code here:
        if (cbMaSP.getSelectedItem() == null || cbms.getSelectedItem() == null || cbkt.getSelectedItem() == null
            || txtSoluong.getText().isEmpty() || txtDongia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }
        try {
            int maSP = Integer.parseInt(cbMaSP.getSelectedItem().toString());
            String mausac = cbms.getSelectedItem().toString();
            int kichco = Integer.parseInt(cbkt.getSelectedItem().toString());
            int sl = Integer.parseInt(txtSoluong.getText().trim());
            float dg = Float.parseFloat(txtDongia.getText().trim());

            boolean ok = cothem ? ct.addChiTiet(maSP, mausac, kichco, sl, dg)
            : ct.updateChiTiet(maSP, mausac, kichco, sl, dg);

            if (ok) {
                JOptionPane.showMessageDialog(this, (cothem ? "Thêm" : "Sửa") + " thành công!");
                showData();
                setNull();
                setButton(true);
                setKhoa(true);
            } else {
                JOptionPane.showMessageDialog(this, (cothem ? "Thêm" : "Sửa") + " thất bại!");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Số lượng/Đơn giá phải là số!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi lưu dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLuuCTMHActionPerformed

    private void btnKLuuCTMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuCTMHActionPerformed
        // TODO add your handling code here:
        setNull();
        setButton(true);
        setKhoa(true);
        tblCTMH.clearSelection();
    }//GEN-LAST:event_btnKLuuCTMHActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaSPActionPerformed
        // TODO add your handling code here:
        if (cbMaSP.getSelectedItem()!=null) {
            try {
                int maSP = Integer.parseInt(cbMaSP.getSelectedItem().toString());
                txtTensp.setText(ct.getTenSPByMa(maSP));
                loadComboBoxMauSac(maSP);
                loadComboBoxKichCo(maSP);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Mã SP không hợp lệ");
            }
        }
    }//GEN-LAST:event_cbMaSPActionPerformed

    private void tblCTMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTMHMouseClicked
        // TODO add your handling code here:
        int row = tblCTMH.getSelectedRow();
        if (row >= 0) {
            int maSP = Integer.parseInt(tblCTMH.getValueAt(row,0).toString());
            cbMaSP.setSelectedItem(String.valueOf(maSP));
            txtTensp.setText(tblCTMH.getValueAt(row,1).toString());
            loadComboBoxMauSac(maSP);
            loadComboBoxKichCo(maSP);
            cbms.setSelectedItem(tblCTMH.getValueAt(row,2).toString());
            cbkt.setSelectedItem(tblCTMH.getValueAt(row,3).toString());
            txtSoluong.setText(tblCTMH.getValueAt(row,4).toString());
            txtDongia.setText(tblCTMH.getValueAt(row,5).toString());
        }
    }//GEN-LAST:event_tblCTMHMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuCTMH;
    private javax.swing.JButton btnLuuCTMH;
    private javax.swing.JButton btnSuaCTMH;
    private javax.swing.JButton btnThemCTMH;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaCTMH;
    private javax.swing.JComboBox<String> cbMaSP;
    private javax.swing.JComboBox<String> cbkt;
    private javax.swing.JComboBox<String> cbms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCTMH;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
