/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import java.sql.*;
import Proccess.PhieuXuat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ngocanh
 */
public class panelPhieuXuat extends javax.swing.JPanel {
    private final PhieuXuat px= new PhieuXuat();
    private boolean cothem = false;  
    private int mapx = -1;
    private final DefaultTableModel tableModel= new DefaultTableModel();
    
    public void loadComboBoxMaNCC() {
        try {
            cbMaKH.removeAllItems();
            List<Integer> list = px.getAllNCC(); 
            for (Integer maKH : list) {
                cbMaKH.addItem(maKH);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nạp danh sách NCC: " + e.getMessage());
        }
    }
    public void loadMANv(){
        try {
            cbMaNVX.removeAllItems();
            List<Integer> list = px.getAllMNV();
            for(Integer manv:list){
                cbMaNVX.addItem(manv);
            }
        } catch (SQLException ex) {
            System.getLogger(frmPhieuXuat.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    public void setnull(){
        txtGhiChuX.setText("");
        txtMaPX.setText("");
        txtNgayXuat.setText("");
        cbMaKH.setSelectedItem(null);
        cbMaNVX.setSelectedItem(null);
    }
    public void setbutton(boolean a){
        btnThemPX.setEnabled(a);
        btnSuaPX.setEnabled(a);
        btnXoaPX.setEnabled(a);
        btnLuuPX.setEnabled(!a);
        btnKLuuPX.setEnabled(!a);
        
    }
    public void setKhoa(boolean a){
        txtGhiChuX.setEditable(!a);
        cbMaKH.setEnabled(!a);
        cbMaNVX.setEnabled(!a);
    }
    public void ShowData() throws SQLException{
        List<PhieuXuat> list = px.getAll(); 
        for(PhieuXuat phieu:list){
            Object[] row = new Object[6];
            row[0] = phieu.getMaPhieuXuat();
            row[1] = phieu.getNgayXuat();
            row[2]=phieu.getMaKH();
            row[3]=phieu.getMaNV();
            row[4]=phieu.getTongTien();
            row[5]=phieu.getGhiChu();     
            tableModel.addRow(row);
        }
    }
    public void ClearData() throws SQLException{
        int n=tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--){
            tableModel.removeRow(i);
        }
    }

    /**
     * Creates new form panelPhieuXuat
     */
    public panelPhieuXuat() throws SQLException {
        initComponents();
        tableModel.setColumnIdentifiers(new Object[]{"Mã phiếu xuất", "Ngày xuất", "Mã KH", "Mã NV", "Tổng tiền", "Ghi chú"});
        tblPX.setModel(tableModel);
        loadMANv();
        loadComboBoxMaNCC();
        ShowData();
        setnull();
        setbutton(true);
        setKhoa(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPX = new javax.swing.JTable();
        btnThemPX = new javax.swing.JButton();
        btnSuaPX = new javax.swing.JButton();
        btnXoaPX = new javax.swing.JButton();
        btnLuuPX = new javax.swing.JButton();
        btnKLuuPX = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtMaPX = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNgayXuat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbMaKH = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbMaNVX = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtGhiChuX = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        btnLamMoiX = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 255, 102)), "Danh sách phiếu xuất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), java.awt.SystemColor.textHighlight)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel3.setVerifyInputWhenFocusTarget(false);

        tblPX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Ngày nhập", "Mã NCC", "Mã NV", "Tổng tiền", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPX.setPreferredSize(new java.awt.Dimension(600, 355));
        tblPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPXMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblPX);

        btnThemPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemPX.setText("Thêm");
        btnThemPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPXActionPerformed(evt);
            }
        });

        btnSuaPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaPX.setText("Sửa");
        btnSuaPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPXActionPerformed(evt);
            }
        });

        btnXoaPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaPX.setText("Xóa");
        btnXoaPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPXActionPerformed(evt);
            }
        });

        btnLuuPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuPX.setText("Lưu");
        btnLuuPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPXActionPerformed(evt);
            }
        });

        btnKLuuPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKLuuPX.setText("Klưu");
        btnKLuuPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuPXActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Mã phiếu xuất");
        jLabel13.setToolTipText("");

        txtMaPX.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Ngày xuất");

        txtNgayXuat.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Mã KH");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Mã NV");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Ghi chú");

        txtGhiChuX.setColumns(20);
        txtGhiChuX.setRows(5);
        jScrollPane6.setViewportView(txtGhiChuX);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setForeground(java.awt.SystemColor.textHighlight);
        jLabel18.setText("Chi tiết phiếu xuất");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        btnLamMoiX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoiX.setText("Làm mới");
        btnLamMoiX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiXActionPerformed(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(198, 198, 198)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(61, 61, 61)
                                        .addComponent(cbMaNVX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(59, 59, 59))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThemPX)
                        .addGap(24, 24, 24)
                        .addComponent(btnSuaPX)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaPX)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuuPX)
                        .addGap(18, 18, 18)
                        .addComponent(btnKLuuPX)
                        .addGap(105, 105, 105)
                        .addComponent(btnLamMoiX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemPX)
                    .addComponent(btnSuaPX)
                    .addComponent(btnXoaPX)
                    .addComponent(btnLuuPX)
                    .addComponent(btnKLuuPX)
                    .addComponent(btnLamMoiX)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbMaNVX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPXMouseClicked
        try {
            // TODO add your handling code here:
            int row=tblPX.getSelectedRow();
            String ma=tblPX.getValueAt(row,0).toString();
            mapx = Integer.parseInt(ma);
            PhieuXuat obj=px.getPhieuXuat(mapx);
            if(obj!=null){
                txtGhiChuX.setText(obj.getGhiChu());
                txtMaPX.setText(String.valueOf(obj.getMaPhieuXuat()));
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                txtNgayXuat.setText(sdf.format(obj.getNgayXuat()));
                cbMaKH.setSelectedItem(obj.getMaKH());
                cbMaNVX.setSelectedItem(obj.getMaNV());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + ex.getMessage());
        }
    }//GEN-LAST:event_tblPXMouseClicked

    private void btnThemPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPXActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(false);
        setKhoa(false);
        cothem=true;
        tblPX.setEnabled(false);
    }//GEN-LAST:event_btnThemPXActionPerformed

    private void btnSuaPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPXActionPerformed
        // TODO add your handling code here:
        String mapn=txtMaPX.getText();
        if(mapn.isEmpty()){
            JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần sửa!");
        }
        else{
            setKhoa(false);
            tblPX.setEnabled(false);
            setbutton(false);
            cothem=false;
        }
    }//GEN-LAST:event_btnSuaPXActionPerformed

    private void btnXoaPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPXActionPerformed
        // TODO add your handling code here:
        String ma=txtMaPX.getText();
        try{
            if(ma.isEmpty()){
                JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần xóa!");
                return;
            }
            int mpx=Integer.parseInt(ma);
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa không!")==JOptionPane.YES_OPTION){
                px.deleteData(mpx);
                ClearData();
                ShowData();
                setnull();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaPXActionPerformed

    private void btnLuuPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPXActionPerformed
        // TODO add your handling code here:
        Object makhObj = cbMaKH.getSelectedItem();
        Object manvObj = cbMaNVX.getSelectedItem();
        String ghichu = txtGhiChuX.getText().trim();
        String maphieu=txtMaPX.getText();

        if(makhObj == null || manvObj == null){
            JOptionPane.showMessageDialog(this,"Vui lòng điền đầy đủ thông tin!");
        }
        else{
            try {
                int makh = (int) makhObj;
                int manv = (int) manvObj;
                PhieuXuat obj = new PhieuXuat();
                java.util.Date now = new java.util.Date();
                obj.setNgayXuat(now);   // tự động lấy thời gian hiện tại
                //            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                //            txtNgayXuat.setText(sdf.format(now));
                obj.setMaKH(makh);
                obj.setMaNV(manv);
                obj.setTongTien(0);
                obj.setGhiChu(ghichu);
                if(cothem==true){
                    px.InsertData(obj);
                }
                else{
                    int maphieunhap = Integer.parseInt(maphieu);
                    obj.setMaPhieuXuat(maphieunhap);
                    px.EditData(obj);
                }
                ClearData();
                ShowData();
                setnull();
                setbutton(true);
                setKhoa(true);
                cothem=false;
                tblPX.setEnabled(true);
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Cập nhật thất bại");
            }
        }
    }//GEN-LAST:event_btnLuuPXActionPerformed

    private void btnKLuuPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuPXActionPerformed
        // TODO add your handling code here:
        setnull();
        setKhoa(true);
        setbutton(true);
    }//GEN-LAST:event_btnKLuuPXActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        try {
            if (mapx == -1) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu nhập nào!");
                return;
            }

            // TRUYỀN selectedMaPN QUA FORM CHI TIẾT
            frmChiTietPhieuXuat fr = new frmChiTietPhieuXuat(mapx);
            //this.setVisible(false);
            fr.setVisible(true);

        } catch (SQLException ex) {
            System.getLogger(frmPhieuXuat.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btnLamMoiXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiXActionPerformed
        try {
            // TODO add your handling code here:
            ClearData();
            ShowData();
        } catch (SQLException ex) {
            System.getLogger(frmPhieuXuat.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnLamMoiXActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String keyword = txtTimKiem.getText().trim();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu xuất để tìm!");
            return;
        }
        try {
            ClearData();
            List<PhieuXuat> list = px.TimKiemPX(keyword);
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu xuất nào!");
            } else {
                for(PhieuXuat phieu : list){
                    Object[] row = new Object[6];
                    row[0] = phieu.getMaPhieuXuat();
                    row[1] = phieu.getNgayXuat();
                    row[2] = phieu.getMaKH();
                    row[3] = phieu.getMaNV();
                    row[4] = phieu.getTongTien();
                    row[5] = phieu.getGhiChu();
                    tableModel.addRow(row);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuPX;
    private javax.swing.JButton btnLamMoiX;
    private javax.swing.JButton btnLuuPX;
    private javax.swing.JButton btnSuaPX;
    private javax.swing.JButton btnThemPX;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaPX;
    private javax.swing.JComboBox<Integer> cbMaKH;
    private javax.swing.JComboBox<Integer> cbMaNVX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblPX;
    private javax.swing.JTextArea txtGhiChuX;
    private javax.swing.JTextField txtMaPX;
    private javax.swing.JTextField txtNgayXuat;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
