/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;
import Proccess.NhaCungCap;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class panelNhaCungCap extends javax.swing.JPanel {
private final NhaCungCap nccProcess = new NhaCungCap();
    private boolean cothem = false;
    private int mancc = -1;
    private final DefaultTableModel tableModel = new DefaultTableModel();
    /**
    /**
     * Creates new form panelNhaCungCap
     */
    public panelNhaCungCap() throws SQLException {
        initComponents();
        tableModel.setColumnIdentifiers(new Object[]{"Mã NCC", "Tên NCC", "Email"});
        tblNCC.setModel(tableModel);

        showData();
        setNull();
        setButton(true);
        setKhoa(true);
    }
private void setNull() {
        txtMaNCC.setText("");
        txtTenNCC.setText("");
        txtEmail.setText("");
    }

    private void setButton(boolean b) {
        btnThemNCC3.setEnabled(b);
        btnSuaNCC.setEnabled(b);
        btnXoaNCC.setEnabled(b);
        btnLuuNCC.setEnabled(!b);
        btnKLuuNCC.setEnabled(!b);
    }

    private void setKhoa(boolean b) {
        txtTenNCC.setEditable(!b);
        txtEmail.setEditable(!b);
    }

    private void clearData() {
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);
        }
    }

    private void showData() throws SQLException {
        clearData();
        List<NhaCungCap> list = nccProcess.getAll();
        for (NhaCungCap n : list) {
            Object[] row = new Object[]{
                n.getMaNCC(),
                n.getTenNCC(),
                n.getEmail()
            };
            tableModel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnThemNCC3 = new javax.swing.JButton();
        btnSuaNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();
        btnLuuNCC = new javax.swing.JButton();
        btnKLuuNCC = new javax.swing.JButton();
        btnThoatNCC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhà Cung Cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 153, 255))); // NOI18N

        btnThemNCC3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemNCC3.setText("Thêm");
        btnThemNCC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCC3ActionPerformed(evt);
            }
        });

        btnSuaNCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaNCC.setText("Sửa");
        btnSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNCCActionPerformed(evt);
            }
        });

        btnXoaNCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaNCC.setText("Xóa");
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });

        btnLuuNCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLuuNCC.setText("Lưu");
        btnLuuNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuNCCActionPerformed(evt);
            }
        });

        btnKLuuNCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKLuuNCC.setText("K.Lưu");
        btnKLuuNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuNCCActionPerformed(evt);
            }
        });

        btnThoatNCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoatNCC.setText("Thoát");
        btnThoatNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatNCCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã NCC:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên NCC:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Email:");

        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên NCC", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNCC);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnThemNCC3)
                .addGap(18, 18, 18)
                .addComponent(btnSuaNCC)
                .addGap(18, 18, 18)
                .addComponent(btnXoaNCC)
                .addGap(18, 18, 18)
                .addComponent(btnLuuNCC)
                .addGap(18, 18, 18)
                .addComponent(btnKLuuNCC)
                .addGap(18, 18, 18)
                .addComponent(btnThoatNCC)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNCC3)
                    .addComponent(btnSuaNCC)
                    .addComponent(btnXoaNCC)
                    .addComponent(btnLuuNCC)
                    .addComponent(btnKLuuNCC)
                    .addComponent(btnThoatNCC))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNCC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCC3ActionPerformed
        // TODO add your handling code here:
        setNull();
        setButton(false);
        setKhoa(false);
        txtMaNCC.setEditable(false); // khóa ô Mã NCC, SQL tự tăng
        cothem = true;
        tblNCC.setEnabled(false);
    }//GEN-LAST:event_btnThemNCC3ActionPerformed

    private void btnSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNCCActionPerformed
        // TODO add your handling code here:
        if (txtMaNCC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy chọn NCC cần sửa!");
        } else {
            setButton(false);
            setKhoa(false);
            txtMaNCC.setEditable(false);
            cothem = false;
            tblNCC.setEnabled(false);
        }
    }//GEN-LAST:event_btnSuaNCCActionPerformed

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        // TODO add your handling code here:
        if (txtMaNCC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy chọn NCC cần xóa!");
            return;
        }
        try {
            int id = Integer.parseInt(txtMaNCC.getText());
            if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?") == JOptionPane.YES_OPTION) {
                nccProcess.deleteData(id);
                showData();
                setNull();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }//GEN-LAST:event_btnXoaNCCActionPerformed

    private void btnLuuNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuNCCActionPerformed
        // TODO add your handling code here:
        String ten = txtTenNCC.getText().trim();
        String email = txtEmail.getText().trim();

        // Kiểm tra thông tin trống
        if (ten.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        // Kiểm tra email hợp lệ
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ!");
            return;
        }

        try {
            NhaCungCap obj = new NhaCungCap();
            obj.setTenNCC(ten);
            obj.setEmail(email);

            if (cothem) {
                if (nccProcess.insertData(obj)) {
                    showData();
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                }
            } else {
                int id = Integer.parseInt(txtMaNCC.getText());
                obj.setMaNCC(id);
                if (nccProcess.editData(obj)) {
                    showData();
                    JOptionPane.showMessageDialog(this, "Sửa thành công!");
                }
            }

            setNull();
            setButton(true);
            setKhoa(true);
            cothem = false;
            tblNCC.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnLuuNCCActionPerformed

    private void btnKLuuNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuNCCActionPerformed
        // TODO add your handling code here:
        setNull();
        setButton(true);
        setKhoa(true);
        tblNCC.setEnabled(true);
    }//GEN-LAST:event_btnKLuuNCCActionPerformed

    private void btnThoatNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatNCCActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatNCCActionPerformed

    private void tblNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNCCMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblNCC.getSelectedRow();
            if (row >= 0) {
                mancc = (int) tblNCC.getValueAt(row, 0);
                NhaCungCap obj = nccProcess.getNCC(mancc);
                if (obj != null) {
                    txtMaNCC.setText(String.valueOf(obj.getMaNCC()));
                    txtTenNCC.setText(obj.getTenNCC());
                    txtEmail.setText(obj.getEmail());
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + ex.getMessage());
        }
    }//GEN-LAST:event_tblNCCMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuNCC;
    private javax.swing.JButton btnLuuNCC;
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnThemNCC3;
    private javax.swing.JButton btnThoatNCC;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
