/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Proccess.BienTheSanPham;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class panelBienTheSanPham extends javax.swing.JPanel {
    public javax.swing.JTable gettbbtsp() {
    return tbbienthesanpham;
    }
    public void loadData(int masp) throws SQLException {
    this.maSP = masp;
    ShowData();
    }
    private final BienTheSanPham bt = new BienTheSanPham();
    //private final DefaultTableModel tableModel= new DefaultTableModel();
    private final DefaultTableModel tableModel = new DefaultTableModel(
    new Object[]{"Mã", "Mã sản phẩm", "Màu sắc", "Kích cỡ", }, 0
    );
    private int maSP;
    private boolean cothem=true;
    public void ShowData() throws SQLException{
        List<BienTheSanPham> list = bt.getListByMaSP(maSP);
        tableModel.setRowCount(0);
        for(BienTheSanPham btsp:list){
            Object[] row = new Object[4];
            row[0]= btsp.getMa();
            row[1]=btsp.getMaSP();
            row[2]=btsp.getMauSac();
            row[3]=btsp.getKichCo();
            tableModel.addRow(row);
        }
    }

   public void setnull(){
        txtma.setText("");
        txtmausac.setText("");
        txtkichco.setText("");
        txtmsp.setText("");
    }
    public void setbutton(boolean a){
        btthem.setEnabled(a);
        btsua.setEnabled(a);
        btxoa.setEnabled(a);
        btluu.setEnabled(!a);
        btkluu.setEnabled(!a);
        
    }
    public void setKhoa(boolean a){
        txtma.setEditable(false);
        txtmausac.setEnabled(!a);
        txtkichco.setEnabled(!a);
        txtmsp.setEditable(false); 
    }

    public panelBienTheSanPham() {
        initComponents();
        tbbienthesanpham.setModel(tableModel); 
        setnull();
        setbutton(true);
        setKhoa(true);
    }

    private boolean validateInput() {
        if (txtmausac.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Màu sắc không được để trống!");
            txtmausac.requestFocus();
            return false;
        }
        if (txtkichco.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kích cỡ không được để trống!");
            txtkichco.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbienthesanpham = new javax.swing.JTable();
        btkluu = new javax.swing.JButton();
        btluu = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        btthem = new javax.swing.JButton();
        txtmsp = new javax.swing.JTextField();
        txtkichco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmausac = new javax.swing.JTextField();

        setBackground(new java.awt.Color(228, 245, 255));
        setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Biến thể sản phẩm");

        tbbienthesanpham.setBackground(new java.awt.Color(255, 251, 241));
        tbbienthesanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Mã sản phẩm", "Màu sắc", "Kích cỡ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbbienthesanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbienthesanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbbienthesanpham);

        btkluu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btkluu.setText("K.Lưu");
        btkluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkluuActionPerformed(evt);
            }
        });

        btluu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btluu.setText("Lưu");
        btluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuActionPerformed(evt);
            }
        });

        btxoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        btsua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btthem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_1.png"))); // NOI18N
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Màu sắc:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Kích cỡ:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã sản phẩm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                                .addComponent(btluu)
                                .addGap(73, 73, 73)
                                .addComponent(btkluu)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmsp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmausac, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkichco, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btthem)
                        .addGap(77, 77, 77)
                        .addComponent(btsua)
                        .addGap(74, 74, 74)
                        .addComponent(btxoa)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btluu)
                            .addComponent(btkluu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtkichco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(txtmausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtmsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsua)
                    .addComponent(btthem)
                    .addComponent(btxoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(false);
        setKhoa(false);
        cothem = true;
        tbbienthesanpham.setEnabled(false);
        txtmsp.setText(String.valueOf(this.maSP));
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        int row = tbbienthesanpham.getSelectedRow();
        if (row >= 0) {
            setbutton(false);
            setKhoa(false);
            cothem = false;
            tbbienthesanpham.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để sửa");
        }
            
    }//GEN-LAST:event_btsuaActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        int row = tbbienthesanpham.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn biến thể để xóa!");
            return;
        }
        try{
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        int ma = Integer.parseInt(tbbienthesanpham.getValueAt(row, 0).toString());
        bt.setMa(ma);
        if (bt.deleteBienThe()) {
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            ShowData();
            setnull();
        }
        else{
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }}
        catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage());
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        // TODO add your handling code here:
        if (!validateInput()) return;
        String mausac = txtmausac.getText().trim();
        String kichco = txtkichco.getText().trim();
        String ma = txtma.getText().trim();
        String masp = txtmsp.getText().trim();
            try {
                int kichcoint = Integer.parseInt(kichco);
                int maspint = this.maSP;
                BienTheSanPham obj = new BienTheSanPham();
                obj.setMauSac(mausac);
                obj.setKichCo(kichcoint);
                obj.setMaSP(maspint);
                 if(cothem==true){

                        bt.addBienThe(obj);}

                else{

                    int maint = Integer.parseInt(ma);

                    obj.setMa(maint);

                    bt.updateBienThe(obj);

                }

                ShowData();

                    setnull();

                    setbutton(true);

                    setKhoa(true);

                    tbbienthesanpham.setEnabled(true);

            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
    }//GEN-LAST:event_btluuActionPerformed

    private void btkluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkluuActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(true);
        setKhoa(true);
        tbbienthesanpham.setEnabled(true);
    }//GEN-LAST:event_btkluuActionPerformed

    private void tbbienthesanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbienthesanphamMouseClicked
        // TODO add your handling code here:                                           
    try {
        int row = tbbienthesanpham.getSelectedRow();
        if (row < 0) return;

        // Lấy mã biến thể (cột 0)
        int maBienThe = Integer.parseInt(tbbienthesanpham.getValueAt(row, 0).toString());

        BienTheSanPham obj = bt.getBienTheSanPham(maBienThe);
        if (obj != null) {
            txtma.setText(String.valueOf(obj.getMa()));
            txtmsp.setText(String.valueOf(obj.getMaSP()));
            txtmausac.setText(obj.getMauSac());
            txtkichco.setText(String.valueOf(obj.getKichCo()));
        }
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + e.getMessage());
    }
    

    }//GEN-LAST:event_tbbienthesanphamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btkluu;
    private javax.swing.JButton btluu;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbbienthesanpham;
    private javax.swing.JTextField txtkichco;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtmausac;
    private javax.swing.JTextField txtmsp;
    // End of variables declaration//GEN-END:variables

}
