/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;
import Proccess.NhanVien;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
/**
 *d
 * @author Admin
 */
public class panelNhanVien extends javax.swing.JPanel {
    public javax.swing.JTable gettbNhanVien() {
        return tbnhanvien;
    }
    private NhanVien nv = new NhanVien();
    private boolean cothem = false;
    private int manv = -1;
    private final DefaultTableModel tableModel= new DefaultTableModel();
    /**
     * Creates new form panelNhanVien
     */
    public panelNhanVien() throws SQLException {
        initComponents();
        tableModel.setColumnIdentifiers(new Object[]{"Họ","Tên", "Giới tính", "Ngày sinh", "Mã nhân viên", "Mật khẩu", "Email", "Địa chỉ", "Vai trò", "Trạng thái", "Ngày tạo"});
        tbnhanvien.setModel(tableModel);
        ShowData();
        setnull();
        setButton(true);
        setKhoa(true);
    }
public void setnull(){
        txtten.setText("");
        txtmnv.setText("");
        txtdiachi.setText("");
        txtngaysinh.setText("");
        txtngaytao.setText("");
        txtho.setText("");
        txtemail.setText("");
        txtpass.setText("");
        cbgioitinh.setSelectedIndex(-1);
        cbtrangthai.setSelectedIndex(-1);
        cbvaitro.setSelectedIndex(-1);
    }
private void setButton(boolean enable) {
        btthem.setEnabled(enable);
        btsua.setEnabled(enable);
        btxoa.setEnabled(enable);
        btluu.setEnabled(!enable);
        btkluu.setEnabled(!enable);
    }
public void setKhoa(boolean enable){
        txtten.setEditable(!enable);
        txtho.setEditable(!enable);
        txtngaysinh.setEditable(!enable);
        txtngaytao.setEditable(!enable);
        txtdiachi.setEditable(!enable);
        txtemail.setEditable(!enable);
        txtpass.setEditable(!enable);
        cbtrangthai.setEnabled(!enable);
        cbgioitinh.setEnabled(!enable);
        cbvaitro.setEnabled(!enable);
    }
public void cleardata() {
        int n=tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--){
            tableModel.removeRow(i);
        }
    }
public void ShowData() throws SQLException {
    SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
    tableModel.setRowCount(0); 
    List<NhanVien> list = nv.getAll();

    for (NhanVien nhv : list) {
        Object[] row = new Object[11];
        // Vai trò (0: Quản lý, 1: Nhân viên kho, 2: Nhân viên thu ngân)
        String vaiTroHienThi;
        if (nhv.getVaiTro() == 0) {
            vaiTroHienThi = "Quản lý";
        } else if (nhv.getVaiTro() == 1) {
            vaiTroHienThi = "Nhân viên kho";
        } else { 
            vaiTroHienThi = "Nhân viên thu ngân";
        }
        
        // Giới tính (1: Nam, 0: Nữ)
        String gioiTinhHienThi = (nhv.getGioiTinh() == 1) ? "Nam" : "Nữ";

        // Trạng thái (1: Hoạt động, 0: Không hoạt động)
        String trangThaiHienThi = (nhv.getTrangThai() == 1) ? "Hoạt động" : "Không hoạt động";
       
        
        // Ngày Sinh
        String ngaySinhHienThi = (nhv.getNgaySinh() != null) 
                                 ? sdfDate.format(nhv.getNgaySinh()) 
                                 : "";
        
        // Ngày Tạo
        String ngayTaoHienThi = (nhv.getNgayTao() != null) 
                                ? sdfDate.format(nhv.getNgayTao()) 
                                : "";
        
        row[0] = nhv.getHo();
        row[1] = nhv.getTen();
        row[2] = gioiTinhHienThi; 
        row[3] = ngaySinhHienThi; 
        row[4] = nhv.getMaNhanVien();
        row[5] = nhv.getMatKhau();
        row[6] = nhv.getEmail();
        row[7] = nhv.getDiaChi();
        row[8] = vaiTroHienThi;   
        row[9] = trangThaiHienThi; 
        row[10] = ngayTaoHienThi;  
        tableModel.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtten = new javax.swing.JTextField();
        cbvaitro = new javax.swing.JComboBox<>();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btxoa = new javax.swing.JButton();
        cbtrangthai = new javax.swing.JComboBox<>();
        btluu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btkluu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        txtngaytao = new javax.swing.JTextField();
        txtmnv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        txttimkiem = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtho = new javax.swing.JTextField();
        cbgioitinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnhanvien = new javax.swing.JTable();
        btlammoi = new javax.swing.JButton();
        bttim = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 245, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 51, 204))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 800));

        cbvaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên kho", "Nhân viên thu ngân" }));

        btthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_1.png"))); // NOI18N
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        btsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Trạng thái: ");

        btxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        cbtrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Không hoạt động" }));

        btluu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btluu.setText("Lưu");
        btluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Ngày tạo:");

        btkluu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btkluu.setText("K.Lưu");
        btkluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkluuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã nhân viên:");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        txtngaytao.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtngaytao.setForeground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Tìm kiếm:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mật khẩu:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Ngày sinh:");

        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });

        txttimkiem.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txttimkiem.setForeground(new java.awt.Color(153, 153, 153));

        txtngaysinh.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtngaysinh.setForeground(new java.awt.Color(153, 153, 153));
        txtngaysinh.setText("yyyy-MM-dd");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Họ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Giới tính:");

        cbgioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbgioitinh.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Vai trò:");

        tbnhanvien.setBackground(new java.awt.Color(255, 251, 241));
        tbnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ", "Tên", "Giới tính", "Ngày sinh", "Mã nhân viên", "Mật khẩu", "Email", "Địa chỉ", "Vai trò", "Trạng thái", "Ngày tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbnhanvien);

        btlammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Restart1.png"))); // NOI18N
        btlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlammoiActionPerformed(evt);
            }
        });

        bttim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        bttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(187, 187, 187)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtho, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmnv, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btsua)
                                                .addGap(99, 99, 99))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btthem)
                                                .addComponent(jLabel6)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btxoa)
                                            .addGap(109, 109, 109))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btluu)
                        .addGap(37, 37, 37)
                        .addComponent(btkluu)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel8)
                                .addGap(45, 45, 45)
                                .addComponent(cbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtngaysinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtngaytao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbtrangthai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btkluu)
                        .addComponent(btluu))
                    .addComponent(bttim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtmnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btsua)
                            .addComponent(btthem)
                            .addComponent(btxoa))
                        .addGap(36, 36, 36)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        setnull();
        setButton(false);
        setKhoa(false);
        cothem=true;
        tbnhanvien.setEnabled(false);
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        String manvtxt=txtmnv.getText().trim();
        if(manvtxt.isEmpty()){
            JOptionPane.showMessageDialog(this,"Hãy chọn nhân viên cần sửa!");
        }
        else{
            setKhoa(false);
            tbnhanvien.setEnabled(false);
            setButton(false);
            cothem=false;
        }
    }//GEN-LAST:event_btsuaActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        String ma=txtmnv.getText();
        try{
            if(ma.isEmpty()){
                JOptionPane.showMessageDialog(this,"Hãy chọn nhân viên cần xóa!");
                return;
            }
            int mnv =Integer.parseInt(ma);
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa không!")==JOptionPane.YES_OPTION){
                nv.delete(mnv);
                JOptionPane.showMessageDialog(this,"Xóa nhân viên thành công!");
                cleardata();
                ShowData();
                setnull();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Xóa thất bại"+ex.getMessage());
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        // TODO add your handling code here:
        String gioitinhStr = (String) cbgioitinh.getSelectedItem();
        String vaitroStr = (String) cbvaitro.getSelectedItem();
        String trangthaiStr = (String) cbtrangthai.getSelectedItem();
        String ho = txtho.getText().trim();
        String ten = txtten.getText().trim();
        String diachi = txtdiachi.getText().trim();
        String email = txtemail.getText().trim();
        String pass = txtpass.getText().trim();
        String ngaysinhStr = txtngaysinh.getText().trim();
        String mnhv = txtmnv.getText().trim();
        
        if(gioitinhStr == null || trangthaiStr == null||vaitroStr == null || ho.isEmpty()
                || ten.isEmpty() || diachi.isEmpty() || email.isEmpty() || pass.isEmpty() || ngaysinhStr.isEmpty() ||(!cothem && mnhv.isEmpty())){
            JOptionPane.showMessageDialog(this,"Vui lòng điền đầy đủ thông tin!");
            return;
        }
        int gioiTinhInt = -1; // -1 là giá trị mặc định báo lỗi
        int vaiTroInt = -1;
        int trangThaiInt = -1;
        if (gioitinhStr.equalsIgnoreCase("Nam")) {
        gioiTinhInt = 1;
        } else if (gioitinhStr.equalsIgnoreCase("Nữ")) {
        gioiTinhInt = 0;
        }
        if (vaitroStr.equalsIgnoreCase("Quản lý")) {
        vaiTroInt = 0;
        } else if (vaitroStr.equalsIgnoreCase("Nhân viên kho")) {
        vaiTroInt = 1;
        } else if (vaitroStr.equalsIgnoreCase("Nhân viên thu ngân")) {
        vaiTroInt = 2;
        }
        if (trangthaiStr.equalsIgnoreCase("Hoạt động")) {
        trangThaiInt = 1;
        } else if (trangthaiStr.equalsIgnoreCase("Không hoạt động")) {
        trangThaiInt = 0;
        }
        if (gioiTinhInt == -1 || vaiTroInt == -1 || trangThaiInt == -1) {
         JOptionPane.showMessageDialog(this, "Lỗi chuyển đổi dữ liệu. Vui lòng kiểm tra lại giá trị JComboBox.");
         return;
        }
        java.util.Date ngaySinhUtil;
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        
            try {
                ngaySinhUtil = formatter.parse(ngaysinhStr);
                NhanVien obj = new NhanVien();  
                java.util.Date ngayTaoUtil = new java.util.Date();
                obj.setHo(ho);
                obj.setNgayTao(ngayTaoUtil);
                obj.setTen(ten);
                obj.setDiaChi(diachi);
                obj.setEmail(email);
                obj.setMatKhau(pass);
                obj.setNgaySinh(ngaySinhUtil);
                obj.setGioiTinh(gioiTinhInt);        
                obj.setVaiTro(vaiTroInt);             
                obj.setTrangThai(trangThaiInt);
                if(cothem==true){
                    obj.setNgayTao(ngayTaoUtil); 
                    nv.insert(obj);
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
                }
                else{
                    int manhvint = Integer.parseInt(mnhv);
                    obj.setMaNhanVien(manhvint);
                    nv.update(obj);
                    JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");
                }
                cleardata();
                ShowData();
                setnull();
                setButton(true);
                setKhoa(true);
                cothem=false;
                tbnhanvien.setEnabled(true);
            }
            catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng ngày sinh. Vui lòng nhập theo định dạng yyyy-MM-dd.");
    }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Cập nhật thất bại");
            }
        
    }//GEN-LAST:event_btluuActionPerformed

    private void btkluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkluuActionPerformed
        // TODO add your handling code here:
        setnull();
        setButton(true);
        setKhoa(true);
    }//GEN-LAST:event_btkluuActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void tbnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnhanvienMouseClicked
        // TODO add your handling code here:\
        try {
            setButton(true);
            setKhoa(true);
        int row = tbnhanvien.getSelectedRow();
        if (row < 0) return;
        String ma = tbnhanvien.getValueAt(row, 4).toString();
        manv = Integer.parseInt(ma);
        NhanVien obj = nv.getNhanVien(manv);
        if (obj != null) {
            SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
            txtho.setText(obj.getHo());
            txtten.setText(obj.getTen());
            txtdiachi.setText(obj.getDiaChi());
            txtemail.setText(obj.getEmail());
            txtpass.setText(obj.getMatKhau());
            txtmnv.setText(String.valueOf(obj.getMaNhanVien()));
            if (obj.getNgaySinh() != null) {
                txtngaysinh.setText(sdfDate.format(obj.getNgaySinh()));
            } else {
                txtngaysinh.setText("");
            }
            
            if (obj.getNgayTao() != null) {
                txtngaytao.setText(sdfDate.format(obj.getNgayTao()));
            } else {
                txtngaytao.setText("");
            }
            String gioiTinhHienThi = (obj.getGioiTinh() == 1) ? "Nam" : "Nữ";
            cbgioitinh.setSelectedItem(gioiTinhHienThi);

           
            String vaiTroHienThi = null;
            if (obj.getVaiTro() == 0) {
                vaiTroHienThi = "Quản lý";
            } else if (obj.getVaiTro() == 1) {
                vaiTroHienThi = "Nhân viên kho";
            } else if (obj.getVaiTro() == 2) {
                vaiTroHienThi = "Nhân viên thu ngân";
            }
            cbvaitro.setSelectedItem(vaiTroHienThi);

      
            String trangThaiHienThi = (obj.getTrangThai() == 1) ? "Hoạt động" : "Không hoạt động";
            cbtrangthai.setSelectedItem(trangThaiHienThi);
        }
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin nhân viên cho mã: " + manv);
        }
        
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + ex.getMessage());
    }
    }//GEN-LAST:event_tbnhanvienMouseClicked

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    private void btlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlammoiActionPerformed
        // TODO add your handling code here:
        try {
            cleardata();
            ShowData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi tải lại dữ liệu: " + ex.getMessage());
        }
    }//GEN-LAST:event_btlammoiActionPerformed

    private void bttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimActionPerformed
        // TODO add your handling code here:
        String keyword = txttimkiem.getText().trim();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin để tìm!");
            return;
        }
        try{
            cleardata();
            List <NhanVien> list = nv.search(keyword);
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên nào!");
                
            }
            else{
                for(NhanVien nhv : list){
                    Object[] row = new Object[11];
                    SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");
                    row [0] = nhv.getHo();
                    row [1] = nhv.getTen();
                    row [2] = (nhv.getGioiTinh()==1) ? "Nam" : "Nữ";
                    row[3] = (nhv.getNgaySinh() != null) ? sdfDate.format(nhv.getNgaySinh()) : "";
                    row [4] = nhv.getMaNhanVien();
                    row [5] = nhv.getMatKhau();
                    row [6] = nhv.getEmail();
                    row [7] = nhv.getDiaChi();
                    String vaiTroHienThi = (nhv.getVaiTro() == 0) ? "Quản lý" : (nhv.getVaiTro() == 1 ? "Nhân viên kho" : "Nhân viên thu ngân");
                    row [8] = vaiTroHienThi;
                    row [9] = (nhv.getTrangThai() == 1) ? "Hoạt động" : "Không hoạt động";
                    row[10] = (nhv.getNgayTao() != null) ? sdfDate.format(nhv.getNgayTao()) : "";
                    tableModel.addRow(row);
            }
        } 
        }
        catch (SQLException e) {
        // Thông báo lỗi SQL chi tiết
        JOptionPane.showMessageDialog(this, "Lỗi truy vấn cơ sở dữ liệu: " + e.getMessage());}
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm!" +e.getMessage());
        }
    }//GEN-LAST:event_bttimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btkluu;
    private javax.swing.JButton btlammoi;
    private javax.swing.JButton btluu;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton bttim;
    private javax.swing.JButton btxoa;
    private javax.swing.JComboBox<String> cbgioitinh;
    private javax.swing.JComboBox<String> cbtrangthai;
    private javax.swing.JComboBox<String> cbvaitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbnhanvien;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtho;
    private javax.swing.JTextField txtmnv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtngaytao;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
