    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;
import Proccess.BienTheSanPham;
import Proccess.SanPham;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
public class panelSanPham extends javax.swing.JPanel {
    public javax.swing.JTable gettbSanPham() {
        return tbsanpham;
    }
    private final SanPham sp = new SanPham();
    private boolean cothem = false;
    private int masp = -1;
    private final DefaultTableModel tablemodel = new DefaultTableModel();

    public panelSanPham() throws SQLException {
        initComponents();
        tablemodel.setColumnIdentifiers(new Object[]{"Tên Sản Phẩm","Mã Sản Phẩm", "Mã NCC", "Giảm giá", "Trạng thái SP"});
        tbsanpham.setModel(tablemodel);
        loadNCC(); // Load danh sách nhà cung cấp vào ComboBox
        showdata();
        setnull();
        setButton(true);
        setKhoa(true);
    }

    // Load danh sách NCC vào ComboBox
    private void loadNCC()  {
        try{
            cbmancc.removeAllItems();
        List<Integer> list = sp.getAllNCC();
        for (Integer maNCC : list) {
            cbmancc.addItem(maNCC);
        }}
        catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Lỗi nạp NCC: "+ e.getMessage());
        }
    }
    public void setnull(){
        txttensp.setText("");
        txtmsp.setText("");
        txtgiamgia.setText("");
        cbtrangthai.setSelectedItem(null);
        cbmancc.setSelectedItem(null);
    }
    private void setButton(boolean enable) {
        btthem.setEnabled(enable);
        btsua.setEnabled(enable);
        btxoa.setEnabled(enable);
        btluuu.setEnabled(!enable);
        btkluu.setEnabled(!enable);
    }
        public void setKhoa(boolean enable){
        txttensp.setEditable(!enable);
        cbmancc.setEnabled(!enable);
        txtgiamgia.setEditable(!enable);
        cbtrangthai.setEnabled(!enable);
    }
    public void cleardata() {
        int n=tablemodel.getRowCount()-1;
        for(int i=n;i>=0;i--){
            tablemodel.removeRow(i);
        }
    }
    public void showdata () throws SQLException{
        List<SanPham> list = sp.getAll();
        for( SanPham sph : list){
            Object[] row = new Object[5];
            row [0] = sph.getTenSanPham();
            row [1] = sph.getMaSanPham();
            row [2] = sph.getMaNCC();
            row [3] = sph.getGiamGia();
            row [4] = sph.getTrangThaiSanPham();
            tablemodel.addRow(row);
        }
    }

    /*private void fillToForm() {
        int row = tbsanpham.getSelectedRow();
        if (row < 0) return;

        txttensp.setText(tbsanpham.getValueAt(row, 0).toString());
        txtmsp.setText(tbsanpham.getValueAt(row, 1).toString());

        int maNCC = Integer.parseInt(tbsanpham.getValueAt(row, 2).toString());
        cbmancc.setSelectedItem(maNCC);
        txtgiamgia.setText(tbsanpham.getValueAt(row, 3).toString());
        cbtrangthai.setSelectedItem(tbsanpham.getValueAt(row, 4).toString());
        
    }*/

    private boolean validateInput() {
        if (txttensp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống!");
            txttensp.requestFocus();
            return false;
        }
        if (cbmancc.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp!");
            cbmancc.requestFocus();
            return false;
        }
        if (txtgiamgia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giảm giá không được để trống!");
            txtgiamgia.requestFocus();
            return false;
        }

        try {
            Double.parseDouble(txtgiamgia.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giảm giá phải là số!");
            txtgiamgia.requestFocus();
            return false;
        }
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLM = new javax.swing.JButton();
        btthem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btsua = new javax.swing.JButton();
        cbmancc = new javax.swing.JComboBox<>();
        txtmsp = new javax.swing.JTextField();
        btxoa = new javax.swing.JButton();
        btluuu = new javax.swing.JButton();
        btkluu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttimkiemsp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtgiamgia = new javax.swing.JTextField();
        txttensp = new javax.swing.JTextField();
        cbtrangthai = new javax.swing.JComboBox<>();
        bttim = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsanpham = new javax.swing.JTable();

        setBackground(new java.awt.Color(228, 245, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản  phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 51, 204))); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 800));

        btnLM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Restart1.png"))); // NOI18N
        btnLM.setMaximumSize(new java.awt.Dimension(36, 37));
        btnLM.setMinimumSize(new java.awt.Dimension(36, 37));
        btnLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLMActionPerformed(evt);
            }
        });

        btthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_1.png"))); // NOI18N
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã sản phẩm:");

        btsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });

        btxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });

        btluuu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btluuu.setText("Lưu");
        btluuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuuActionPerformed(evt);
            }
        });

        btkluu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btkluu.setText("K.Lưu");
        btkluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkluuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã nhà cung cấp:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Trạng thái SP:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Tìm kiếm:");

        txttimkiemsp.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Giảm giá:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        cbtrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn hàng", "Hết hàng" }));

        bttim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        bttim.setPreferredSize(new java.awt.Dimension(26, 27));
        bttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimActionPerformed(evt);
            }
        });

        tbsanpham.setBackground(new java.awt.Color(255, 251, 241));
        tbsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Mã sản phẩm", "Mã NCC", "Giảm giá", "Trạng thái SP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbsanpham);
        if (tbsanpham.getColumnModel().getColumnCount() > 0) {
            tbsanpham.getColumnModel().getColumn(0).setResizable(false);
            tbsanpham.getColumnModel().getColumn(1).setResizable(false);
            tbsanpham.getColumnModel().getColumn(2).setResizable(false);
            tbsanpham.getColumnModel().getColumn(3).setResizable(false);
            tbsanpham.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnLM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimkiemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btluuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btkluu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btthem, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(119, 119, 119)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmsp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbmancc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(btsua)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btxoa))
                                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttimkiemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnLM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btluuu)
                        .addComponent(btkluu)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtmsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbmancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtgiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btthem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btsua, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btxoa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLMActionPerformed
        try {
            cleardata();
            showdata();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi tải lại dữ liệu: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnLMActionPerformed

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        // TODO add your handling code here:
        
        setnull();
        setButton(false);
        setKhoa(false);
        cothem = true;
        tbsanpham.setEnabled(false); // 
        
    }//GEN-LAST:event_btthemActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        // TODO add your handling code here:
        String masp=txtmsp.getText();
        if (masp.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm để sửa!");
            return;
        }
        setKhoa(false);
        tbsanpham.setEnabled(false);
        setButton(false);
        cothem = false;
    }//GEN-LAST:event_btsuaActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        // TODO add your handling code here:
        String ma=txtmsp.getText();
        try{
            if(ma.isEmpty()){
                JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần xóa!");
                return;
            }
            int mpn=Integer.parseInt(ma);
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa không!")==JOptionPane.YES_OPTION){
                sp.delete(mpn);
                cleardata();
                showdata();
                setnull();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Xóa thất bại");
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btluuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuuActionPerformed
        // TODO add your handling code here:
        if (!validateInput()) return;
        Object manccObj = cbmancc.getSelectedItem();
        Object trangthaiObj = cbtrangthai.getSelectedItem();
        String trangthaiStr = trangthaiObj.toString();
        String tensp = txttensp.getText().trim();
        String masp = txtmsp.getText();
        String giamgia = txtgiamgia.getText().trim();
        Double giamgiadb = Double.parseDouble(giamgia); 
            try {
                int mancc = (int) manccObj;
                //int trangthai = Integer.parseInt(trangthaiStr); 
                SanPham obj = new SanPham();
                obj.setMaNCC(mancc);
                obj.setTrangThaiSanPham(trangthaiStr);
                obj.setTenSanPham(tensp);
                obj.setGiamGia(giamgiadb);
                if(cothem==true){
                        sp.insert(obj);}
                else{
                    int maspInt = Integer.parseInt(masp);
                    obj.setMaSanPham(maspInt);
                    sp.update(obj);
                }
                cleardata();
                showdata();
                setnull();
                setButton(true);
                setKhoa(true);
                cothem=false;
                tbsanpham.setEnabled(true);
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
                
    }//GEN-LAST:event_btluuuActionPerformed

    private void tbsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsanphamMouseClicked
        // TODO add your handling code here:
       try {
        int row = tbsanpham.getSelectedRow();
        String ma = tbsanpham.getValueAt(row, 1).toString();
        masp = Integer.parseInt(ma);
        SanPham obj = sp.getSanPham(masp);
        if (obj != null) {
            txttensp.setText(obj.getTenSanPham());
            txtmsp.setText(String.valueOf(obj.getMaSanPham()));
            cbmancc.setSelectedItem(obj.getMaNCC());
            cbtrangthai.setSelectedItem(obj.getTrangThaiSanPham());
            txtgiamgia.setText(String.valueOf(obj.getGiamGia()));
        }
        panelBienTheSanPham chiTietPanel = new panelBienTheSanPham();
        chiTietPanel.loadData(masp);
        chiTietPanel.setVisible(true);

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + ex.getMessage());
    }
    }//GEN-LAST:event_tbsanphamMouseClicked

    private void btkluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkluuActionPerformed
        // TODO add your handling code here:S
        setnull();
        setKhoa(true);
        setButton(true);
       
    }//GEN-LAST:event_btkluuActionPerformed

    private void bttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimActionPerformed
        // TODO add your handling code here:
        String keyword = txttimkiemsp.getText().trim();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin để tìm!");
            return;
        }
        try{
            cleardata();
            List <SanPham> list = sp.search(keyword);
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm nào!");
                
            }
            else{
                for(SanPham sph : list){
                    Object[] row = new Object[5];
                    row [0] = sph.getTenSanPham();
                    row [1] = sph.getMaSanPham();
                    row [2] = sph.getMaNCC();
                    row [3] = sph.getGiamGia();
                    row [4] = sph.getTrangThaiSanPham();
                    tablemodel.addRow(row);
            }
        } 
        }
        catch (SQLException e) {
        // Thông báo lỗi SQL chi tiết
        JOptionPane.showMessageDialog(this, "Lỗi truy vấn cơ sở dữ liệu: " + e.getMessage());}
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm!" +e.getMessage());
        }
    }//GEN-LAST:event_bttimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btkluu;
    private javax.swing.JButton btluuu;
    private javax.swing.JButton btnLM;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton bttim;
    private javax.swing.JButton btxoa;
    private javax.swing.JComboBox<Integer> cbmancc;
    private javax.swing.JComboBox<String> cbtrangthai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbsanpham;
    private javax.swing.JTextField txtgiamgia;
    private javax.swing.JTextField txtmsp;
    private javax.swing.JTextField txttensp;
    private javax.swing.JTextField txttimkiemsp;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    Object gettbsanpham() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
