/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import java.sql.*;
import Proccess.PhieuXuat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ngocanh
 */
public class panelPhieuXuat extends javax.swing.JPanel {
    public javax.swing.JTable getTblPhieuXuat() {
    return tblPX;
    }
    private final int userRole;
    private final PhieuXuat px= new PhieuXuat();
    private boolean cothem = false;  
    private int mapx = -1;
    private final DefaultTableModel tableModel= new DefaultTableModel();
    
//    public void loadComboBoxMaKH() {
//        try {
//            cbMaKH.removeAllItems();
//            List<Integer> list = px.getAllKH(); 
//            for (Integer maKH : list) {
//                cbMaKH.addItem(maKH);
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(this, "Lỗi nạp danh sách NCC: " + e.getMessage());
//        }
//    }
    public void loadMANv(){
        try {
            cbMaNVX.removeAllItems();
            List<Integer> list = px.getAllMNV();
            for(Integer manv:list){
                cbMaNVX.addItem(manv);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    public void loadmbh(){
        try {
            cbMaBH.removeAllItems();
            List<Integer> list = px.getmabh();
            for(Integer mabh:list){
                cbMaBH.addItem(mabh);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    public void setnull(){
        txtGhiChuX.setText("");
        txtMaPX.setText("");
        txtNgayXuat.setText("");
        cbMaNVX.setSelectedItem(null);
        cbMaBH.setSelectedItem(null);
    }
    public void setbutton(boolean a){
        btnLuuPX.setEnabled(!a);
        btnKLuuPX.setEnabled(!a);
        if (a) {
        if (this.userRole == 2) {
            btnThemPX.setEnabled(true);
            btnSuaPX.setEnabled(false);
            btnXoaPX.setEnabled(false);
        } else if (this.userRole == 0) {
            btnThemPX.setEnabled(false); // Quản lý không được thêm
         
        } else {
            // Trường hợp khác (ví dụ: nhanvienkho)
            btnThemPX.setEnabled(false);
            btnSuaPX.setEnabled(false);
            btnXoaPX.setEnabled(false);
        }
    } else {
        // Chế độ Sửa/Thêm (a=false): chỉ cần đảm bảo nút Lưu/Klưu được bật, các nút chính bị tắt
        btnThemPX.setEnabled(false);
        btnSuaPX.setEnabled(false);
        btnXoaPX.setEnabled(false);
    
}
        
    }
     public void phanquyenbtn() {
    // Luôn khóa các nút chức năng mặc định (vì hàm setbutton(true) không được gọi nữa)
    btnThemPX.setEnabled(false);
    btnSuaPX.setEnabled(false);
    btnXoaPX.setEnabled(false);
    btnLuuPX.setEnabled(false);
    btnKLuuPX.setEnabled(false); // Phân quyền chi tiết
    if (this.userRole == 0) {
        btnSuaPX.setEnabled(true);
        btnXoaPX.setEnabled(true);
    } else if (this.userRole == 2) {
        // Nhân viên tn: Chỉ được Thêm
        btnThemPX.setEnabled(true);
    } 
    
    // Vô hiệu hóa nút Lưu/Klưu cho đến khi nhấn Thêm/Sửa
    btnLuuPX.setEnabled(false);
    btnKLuuPX.setEnabled(false);
}
    public void setKhoa(boolean a){
        txtGhiChuX.setEditable(!a);
        cbMaNVX.setEnabled(!a);
        cbMaBH.setEnabled(!a);
    }
    public void ShowData() throws SQLException{
        List<PhieuXuat> list = px.getAll(); 
        for(PhieuXuat phieu:list){
            Object[] row = new Object[7];
            row[0] = phieu.getMaBanHang();
            row[1] = phieu.getMaPhieuXuat();
            row[2] = phieu.getNgayXuat();
            row[3]=phieu.getMaNV();
            row[4]=phieu.getTongTien();
            row[5]=phieu.getGhiChu();     
            tableModel.addRow(row);
        }
    }
    public void ClearData() throws SQLException{
        int n=tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--){
            tableModel.removeRow(i);
        }
    }
    public panelPhieuXuat(int vaiTro) throws SQLException {
        initComponents();
        this.userRole = vaiTro;
        tableModel.setColumnIdentifiers(new Object[]{"Mã BH", "Mã phiếu xuất", "Ngày xuất", "Mã NV", "Tổng tiền", "Ghi chú"});
        tblPX.setModel(tableModel);
        loadmbh();
        loadMANv();
//        loadComboBoxMaKH();
        ShowData();
        setnull();
        phanquyenbtn();
        setKhoa(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChuX = new javax.swing.JTextArea();
        btnKLuuPX = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaPX = new javax.swing.JTextField();
        btnLMX = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayXuat = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPX = new javax.swing.JTable();
        btnTim = new javax.swing.JButton();
        btnThemPX = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSuaPX = new javax.swing.JButton();
        cbMaNVX = new javax.swing.JComboBox<>();
        btnXoaPX = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnLuuPX = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbMaBH = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(700, 800));

        jPanel3.setBackground(new java.awt.Color(228, 245, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 255, 102)), "Danh sách phiếu xuất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 800));
        jPanel3.setVerifyInputWhenFocusTarget(false);

        txtGhiChuX.setColumns(20);
        txtGhiChuX.setRows(5);
        jScrollPane2.setViewportView(txtGhiChuX);

        btnKLuuPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKLuuPX.setText("Klưu");
        btnKLuuPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuPXActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã phiếu xuất");

        txtMaPX.setEditable(false);

        btnLMX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLMX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Restart1.png"))); // NOI18N
        btnLMX.setPreferredSize(new java.awt.Dimension(36, 37));
        btnLMX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLMXActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ngày xuất");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Tìm kiếm:");

        txtNgayXuat.setEditable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 450));

        tblPX.setBackground(new java.awt.Color(255, 251, 241));
        tblPX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã BH", "Mã phiếu nhập", "Ngày nhập", "Mã NCC", "Mã NV", "Tổng tiền", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPX.setPreferredSize(new java.awt.Dimension(700, 500));
        tblPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPXMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPX);

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnThemPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_1.png"))); // NOI18N
        btnThemPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPXActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã NV");

        btnSuaPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btnSuaPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPXActionPerformed(evt);
            }
        });

        btnXoaPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaPX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btnXoaPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPXActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ghi chú");

        btnLuuPX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuPX.setText("Lưu");
        btnLuuPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPXActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mã BH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnThemPX)
                                .addGap(91, 91, 91)
                                .addComponent(btnSuaPX))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMaBH, 0, 90, Short.MAX_VALUE)
                                    .addComponent(cbMaNVX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLMX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTim))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnLuuPX)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnKLuuPX)))
                                .addContainerGap(54, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnXoaPX)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLMX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnTim))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTimKiem)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(btnKLuuPX)
                                .addComponent(btnLuuPX)))))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(txtNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbMaBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbMaNVX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemPX)
                    .addComponent(btnSuaPX)
                    .addComponent(btnXoaPX))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKLuuPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuPXActionPerformed
        // TODO add your handling code here:
        setnull();
        setKhoa(true);
        phanquyenbtn();
        tblPX.setEnabled(true);
    }//GEN-LAST:event_btnKLuuPXActionPerformed

    private void btnLMXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLMXActionPerformed
        // TODO add your handling code here:
        try {
            ClearData();
            ShowData();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLMXActionPerformed

    private void tblPXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPXMouseClicked

        try {
            int row = tblPX.getSelectedRow();
            String ma = tblPX.getValueAt(row, 1).toString();
            mapx = Integer.parseInt(ma);
            PhieuXuat obj = px.getPhieuXuat(mapx);
            if (obj != null) {
                txtGhiChuX.setText(obj.getGhiChu());
                txtMaPX.setText(String.valueOf(obj.getMaPhieuXuat()));
                txtNgayXuat.setText(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(obj.getNgayXuat()));
                cbMaNVX.setSelectedItem(obj.getMaNV());
                cbMaBH.setSelectedItem(obj.getMaBanHang());
            }
            if (this.userRole == 0) {
            btnSuaPX.setEnabled(true);
            btnXoaPX.setEnabled(true);
        } else {
            btnSuaPX.setEnabled(false);
            btnXoaPX.setEnabled(false);
        }

            // --- HIỂN THỊ CHI TIẾT ---
            panelChiTietPhieuXuat chiTietPanel = new panelChiTietPhieuXuat(userRole);
            chiTietPanel.loadData(mapx);
            chiTietPanel.setVisible(true);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + ex.getMessage());
        }
    }//GEN-LAST:event_tblPXMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String keyword = txtTimKiem.getText().trim();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu xuất để tìm!");
            return;
        }
        try {
            ClearData();
            List<PhieuXuat> list = px.TimKiemPX(keyword);
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu xuất nào!");
            } else {
                for(PhieuXuat phieu : list){
                    Object[] row = new Object[7];
                    row[0] = phieu.getMaBanHang();
                    row[1] = phieu.getMaPhieuXuat();
                    row[2] = phieu.getNgayXuat();
                    row[3] = phieu.getMaNV();
                    row[4] = phieu.getTongTien();
                    row[5] = phieu.getGhiChu();
                    tableModel.addRow(row);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPXActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(false);
        setKhoa(false);
        cothem=true;
        tblPX.setEnabled(false);
    }//GEN-LAST:event_btnThemPXActionPerformed

    private void btnSuaPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPXActionPerformed
        // TODO add your handling code here:
        String mapx=txtMaPX.getText();
        if(mapx.isEmpty()){
            JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần sửa!");
        }
        else{
            setKhoa(false);
            tblPX.setEnabled(false);
            setbutton(false);
            cothem=false;
        }
    }//GEN-LAST:event_btnSuaPXActionPerformed

    private void btnXoaPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPXActionPerformed
        // TODO add your handling code here:
        String ma=txtMaPX.getText();
        try{
            if(ma.isEmpty()){
                JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần xóa!");
                return;
            }
            int mpx=Integer.parseInt(ma);
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa không!")==JOptionPane.YES_OPTION){
                px.deleteData(mpx);
                ClearData();
                ShowData();
                setnull();
            }
        }catch(Exception ex){
            ex.printStackTrace();
             JOptionPane.showMessageDialog(this,"Xóa thất bại\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnXoaPXActionPerformed

    private void btnLuuPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPXActionPerformed
        // TODO add your handling code here:
        Object manvObj = cbMaNVX.getSelectedItem();
        String ghichu = txtGhiChuX.getText().trim();
        String maphieu=txtMaPX.getText();
        Object mabhObj = cbMaBH.getSelectedItem();
        if(manvObj == null||mabhObj == null){
            JOptionPane.showMessageDialog(this,"Vui lòng điền đầy đủ thông tin!");
        }

        else{
            try {
                int mabh = (int) mabhObj;
                int manv = (int) manvObj;
                PhieuXuat obj = new PhieuXuat();
                java.util.Date now = new java.util.Date();
                obj.setNgayXuat(now);   // tự động lấy thời gian hiện tại
                //            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                //            txtNgayNhap.setText(sdf.format(now));
                obj.setMaNV(manv);
                obj.setTongTien(0);
                obj.setGhiChu(ghichu);
                obj.setMaBanHang(mabh);
                if(cothem==true){
                    px.InsertData(obj);
                }
                else{
                    int maphieunhap = Integer.parseInt(maphieu);
                    obj.setMaPhieuXuat(maphieunhap);
                    px.EditData(obj);
                }
                ClearData();
                ShowData();
                setnull();
                phanquyenbtn();
                setKhoa(true);
                cothem=false;
                tblPX.setEnabled(true);
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Cập nhật thất bại");
            }
        }
    }//GEN-LAST:event_btnLuuPXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuPX;
    private javax.swing.JButton btnLMX;
    private javax.swing.JButton btnLuuPX;
    private javax.swing.JButton btnSuaPX;
    private javax.swing.JButton btnThemPX;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaPX;
    private javax.swing.JComboBox<Integer> cbMaBH;
    private javax.swing.JComboBox<Integer> cbMaNVX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPX;
    private javax.swing.JTextArea txtGhiChuX;
    private javax.swing.JTextField txtMaPX;
    private javax.swing.JTextField txtNgayXuat;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
