/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Proccess.ChiTietPhieuNhap;
import java.sql.*;
import Proccess.PhieuNhap;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngocanh
 */
public class panelPhieuNhap extends javax.swing.JPanel {
    public javax.swing.JTable getTblPhieuNhap() {
    return tblPN;
    }
    private final PhieuNhap pn= new PhieuNhap();
    private boolean cothem = false;  
    private int mapn = -1;
    private final DefaultTableModel tableModel= new DefaultTableModel();
    
    public void loadComboBoxMaNCC() {
        try {
            cbMaNCC.removeAllItems();
            List<Integer> list = pn.getAllNCC(); 
            for (Integer maNCC : list) {
                cbMaNCC.addItem(maNCC);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nạp danh sách NCC: " + e.getMessage());
        }
    }
    public void loadMANv(){
        try {
            cbMaNV.removeAllItems();
            List<Integer> list = pn.getAllMNV();
            for(Integer manv:list){
                cbMaNV.addItem(manv);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    public void loadmmh(){
        try {
            cbMaMH.removeAllItems();
            List<Integer> list = pn.getmamh();
            for(Integer mamh:list){
                cbMaMH.addItem(mamh);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    public void setnull(){
        txtGhiChu.setText("");
        txtMaPN.setText("");
        txtNgayNhap.setText("");
        cbMaNCC.setSelectedItem(null);
        cbMaNV.setSelectedItem(null);
        cbMaMH.setSelectedItem(null);
    }
    public void setbutton(boolean a){
        btnThemPN.setEnabled(a);
        btnSuaPN.setEnabled(a);
        btnXoaPN.setEnabled(a);
        btnLuuPN.setEnabled(!a);
        btnKLuuPN.setEnabled(!a);
        
    }
    public void setKhoa(boolean a){
        txtGhiChu.setEditable(!a);
        cbMaNCC.setEnabled(!a);
        cbMaNV.setEnabled(!a);
        cbMaMH.setEnabled(!a);
    }
    public void ShowData() throws SQLException{
        List<PhieuNhap> list = pn.getAll(); 
        for(PhieuNhap phieu:list){
            Object[] row = new Object[7];
            row[0] = phieu.getMaMuaHang();
            row[1] = phieu.getMaPhieuNhap();
            row[2] = phieu.getNgayNhap();
            row[3]=phieu.getMaNCC();
            row[4]=phieu.getMaNV();
            row[5]=phieu.getTongTien();
            row[6]=phieu.getGhiChu();     
            tableModel.addRow(row);
        }
    }
    public void ClearData() throws SQLException{
        int n=tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--){
            tableModel.removeRow(i);
        }
    }

    /**
     * Creates new form panelPhieuNhap
     */
    public panelPhieuNhap() throws SQLException {
        initComponents();
        tableModel.setColumnIdentifiers(new Object[]{"Mã MH","Mã phiếu nhập", "Ngày nhập", "Mã NCC", "Mã NV", "Tổng tiền", "Ghi chú"});
        tblPN.setModel(tableModel);
        loadmmh();
        loadMANv();
        loadComboBoxMaNCC();
        ShowData();
        setnull();
        setbutton(true);
        setKhoa(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPN = new javax.swing.JTable();
        btnThemPN = new javax.swing.JButton();
        btnSuaPN = new javax.swing.JButton();
        btnXoaPN = new javax.swing.JButton();
        btnLuuPN = new javax.swing.JButton();
        btnKLuuPN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbMaNCC = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnLM = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbMaMH = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(800, 800));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 255, 102)), "Danh sách phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), java.awt.SystemColor.textHighlight)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 800));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 450));

        tblPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã MH", "Mã phiếu nhập", "Ngày nhập", "Mã NCC", "Mã NV", "Tổng tiền", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPN.setPreferredSize(new java.awt.Dimension(700, 500));
        tblPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPN);

        btnThemPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plus_1.png"))); // NOI18N
        btnThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPNActionPerformed(evt);
            }
        });

        btnSuaPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btnSuaPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPNActionPerformed(evt);
            }
        });

        btnXoaPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btnXoaPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPNActionPerformed(evt);
            }
        });

        btnLuuPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuPN.setText("Lưu");
        btnLuuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPNActionPerformed(evt);
            }
        });

        btnKLuuPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKLuuPN.setText("Klưu");
        btnKLuuPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKLuuPNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã phiếu nhập");

        txtMaPN.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ngày nhập");

        txtNgayNhap.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã NCC");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã NV");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        btnLM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Restart1.png"))); // NOI18N
        btnLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLMActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm kiếm");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Mã MH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnLM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemPN))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSuaPN)
                        .addGap(95, 95, 95)
                        .addComponent(btnXoaPN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim)
                        .addGap(77, 77, 77)
                        .addComponent(btnLuuPN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKLuuPN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayNhap)
                            .addComponent(cbMaNV, 0, 105, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(btnKLuuPN)
                    .addComponent(btnLuuPN))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuaPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPNMouseClicked
       try {
        int row = tblPN.getSelectedRow();
        String ma = tblPN.getValueAt(row, 1).toString();
        mapn = Integer.parseInt(ma);
        PhieuNhap obj = pn.getPhieuNhap(mapn);
        if (obj != null) {
            txtGhiChu.setText(obj.getGhiChu());
            txtMaPN.setText(String.valueOf(obj.getMaPhieuNhap()));
            txtNgayNhap.setText(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(obj.getNgayNhap()));
            cbMaNCC.setSelectedItem(obj.getMaNCC());
            cbMaNV.setSelectedItem(obj.getMaNV());
            cbMaMH.setSelectedItem(obj.getMaMuaHang());
        }
        panelChiTietPhieuNhap chiTietPanel = new panelChiTietPhieuNhap();
        chiTietPanel.loadData(mapn);
        chiTietPanel.setVisible(true);

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lỗi đọc dữ liệu: " + ex.getMessage());
    }
    }//GEN-LAST:event_tblPNMouseClicked

    private void btnThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPNActionPerformed
        // TODO add your handling code here:
        setnull();
        setbutton(false);
        setKhoa(false);
        cothem=true;
        tblPN.setEnabled(false);

    }//GEN-LAST:event_btnThemPNActionPerformed

    private void btnSuaPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPNActionPerformed
        // TODO add your handling code here:
        String mapn=txtMaPN.getText();
        if(mapn.isEmpty()){
            JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần sửa!");
        }
        else{
            setKhoa(false);
            tblPN.setEnabled(false);
            setbutton(false);
            cothem=false;
        }
    }//GEN-LAST:event_btnSuaPNActionPerformed

    private void btnXoaPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPNActionPerformed
        // TODO add your handling code here:
        String ma=txtMaPN.getText();
        try{
            if(ma.isEmpty()){
                JOptionPane.showMessageDialog(this,"Hãy chọn sản phẩm cần xóa!");
                return;
            }
            int mpn=Integer.parseInt(ma);
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa không!")==JOptionPane.YES_OPTION){
                pn.deleteData(mpn);
                ClearData();
                ShowData();
                setnull();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaPNActionPerformed

    private void btnLuuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPNActionPerformed
        // TODO add your handling code here:
        Object manccObj = cbMaNCC.getSelectedItem();
        Object manvObj = cbMaNV.getSelectedItem();
        String ghichu = txtGhiChu.getText().trim();
        String maphieu=txtMaPN.getText();
        Object mamhObj = cbMaMH.getSelectedItem();
        if(manccObj == null || manvObj == null||mamhObj == null){
            JOptionPane.showMessageDialog(this,"Vui lòng điền đầy đủ thông tin!");
        }

        else{
            try {
                int mamh = (int) mamhObj;
                int mancc = (int) manccObj;
                int manv = (int) manvObj;
                PhieuNhap obj = new PhieuNhap();
                java.util.Date now = new java.util.Date();
                obj.setMaMuaHang(mamh);
                obj.setNgayNhap(now);   // tự động lấy thời gian hiện tại
                //            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                //            txtNgayNhap.setText(sdf.format(now));
                obj.setMaNCC(mancc);
                obj.setMaNV(manv);
                obj.setTongTien(0);
                obj.setGhiChu(ghichu);
                if(cothem==true){
                    pn.InsertData(obj);
                }
                else{
                    int maphieunhap = Integer.parseInt(maphieu);
                    obj.setMaPhieuNhap(maphieunhap);
                    pn.EditData(obj);
                }
                ClearData();
                ShowData();
                setnull();
                setbutton(true);
                setKhoa(true);
                cothem=false;
                tblPN.setEnabled(true);
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Cập nhật thất bại");
            }
        }
    }//GEN-LAST:event_btnLuuPNActionPerformed

    private void btnKLuuPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKLuuPNActionPerformed
        // TODO add your handling code here:
        setnull();
        setKhoa(true);
        setbutton(true);
    }//GEN-LAST:event_btnKLuuPNActionPerformed

    private void btnLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLMActionPerformed
        // TODO add your handling code here:
        try {
            ClearData();
            ShowData();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLMActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String keyword = txtTK.getText().trim();
        if(keyword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phiếu xuất để tìm!");
            return;
        }
        try {
            ClearData();
            List<PhieuNhap> list = pn.TimKiemPN(keyword);
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu xuất nào!");
            } else {
                for(PhieuNhap phieu : list){
                    Object[] row = new Object[7];
                    row[0] = phieu.getMaMuaHang();
                    row[1] = phieu.getMaPhieuNhap();
                    row[2] = phieu.getNgayNhap();
                    row[3] = phieu.getMaNCC();
                    row[4] = phieu.getMaNV();
                    row[5] = phieu.getTongTien();
                    row[6] = phieu.getGhiChu();
                    tableModel.addRow(row);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuuPN;
    private javax.swing.JButton btnLM;
    private javax.swing.JButton btnLuuPN;
    private javax.swing.JButton btnSuaPN;
    private javax.swing.JButton btnThemPN;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaPN;
    private javax.swing.JComboBox<Integer> cbMaMH;
    private javax.swing.JComboBox<Integer> cbMaNCC;
    private javax.swing.JComboBox<Integer> cbMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPN;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
