/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import java.sql.*;
import Database.Connect;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngocanh
 */
public class panelThongKe extends javax.swing.JPanel {
    private final Connect cn=new Connect();
    public void loadThongKeSanPham() {
        String sql = "SELECT sp.MaSanPham, sp.TenSanPham, " +
        "       ISNULL(nhap.TongNhap, 0) AS TongNhap, " +
        "       ISNULL(xuat.TongXuat, 0) AS TongXuat, " +
        "       ISNULL(nhap.TongNhap, 0) - ISNULL(xuat.TongXuat, 0) AS Ton " +
        "FROM SAN_PHAM sp " +
        "LEFT JOIN ( " +
        "    SELECT MaSanPham, SUM(SoLuong) AS TongNhap " +
        "    FROM CHI_TIET_PHIEU_NHAP " +
        "    GROUP BY MaSanPham " +
        ") AS nhap ON sp.MaSanPham = nhap.MaSanPham " +
        "LEFT JOIN ( " +
        "    SELECT MaSanPham, SUM(SoLuong) AS TongXuat " +
        "    FROM CHI_TIET_PHIEU_XUAT " +
        "    GROUP BY MaSanPham " +
        ") AS xuat ON sp.MaSanPham = xuat.MaSanPham " +
        "ORDER BY sp.MaSanPham";

    try (Connection conn = new Connect().connectSQL();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        while (rs.next()) {
            Object[] row = new Object[] {
                rs.getInt("MaSanPham"),
                rs.getString("TenSanPham"),
                rs.getInt("TongNhap"),
                rs.getInt("TongXuat"),
                rs.getInt("Ton")
            };
            model.addRow(row);
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    public panelThongKe() {
        initComponents();
        loadThongKeSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống kê sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), java.awt.SystemColor.textHighlight)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Tổng số lượng nhập", "Tổng số lượng xuất", "Tồn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
